from module.base.button import Button
from module.base.template import Template

# This file is generated by module.dev_tools.asset_extract.
# Don't modified it manually.

C2 = Button(area=(471, 577, 512, 614), color=(117, 104, 72), button=(471, 577, 512, 614), file='./assets/campaign/C2.png')
CHAPTER_NEXT = Button(area=(1216, 362, 1232, 388), color=(121, 150, 198), button=(1216, 362, 1232, 388), file='./assets/campaign/CHAPTER_NEXT.png')
CHAPTER_PREV = Button(area=(42, 360, 58, 387), color=(105, 133, 169), button=(42, 360, 58, 387), file='./assets/campaign/CHAPTER_PREV.png')
D3 = Button(area=(842, 284, 881, 323), color=(104, 91, 63), button=(842, 284, 881, 323), file='./assets/campaign/D3.png')
EVENT_20200312CN_SP3 = Button(area=(797, 414, 839, 450), color=(118, 105, 72), button=(797, 414, 839, 450), file='./assets/campaign/EVENT_20200312CN_SP3.png')
MODE_CHANGE = Button(area=(69, 644, 131, 653), color=(216, 114, 114), button=(28, 647, 143, 699), file='./assets/campaign/MODE_CHANGE.png')
OCR_OIL = Button(area=(635, 28, 715, 48), color=(74, 75, 84), button=(635, 28, 715, 48), file='./assets/campaign/OCR_OIL.png')
TEMPLATE_STAGE_CLEAR = Template(area=(432, 201, 471, 240), color=(117, 104, 71), button=(432, 201, 471, 240), file='./assets/campaign/TEMPLATE_STAGE_CLEAR.png')
