from module.base.button import Button
from module.base.template import Template

# This file is generated by module.dev_tools.asset_extract.
# Don't modified it manually.

CHAPTER_NEXT = Button(area=(1216, 362, 1232, 388), color=(121, 150, 198), button=(1216, 362, 1232, 388), file='./assets/campaign/CHAPTER_NEXT.png')
CHAPTER_PREV = Button(area=(42, 360, 58, 387), color=(105, 133, 169), button=(42, 360, 58, 387), file='./assets/campaign/CHAPTER_PREV.png')
MODE_CHANGE = Button(area=(69, 644, 131, 653), color=(216, 114, 114), button=(28, 647, 143, 699), file='./assets/campaign/MODE_CHANGE.png')
OCR_OIL = Button(area=(635, 28, 715, 48), color=(74, 75, 84), button=(635, 28, 715, 48), file='./assets/campaign/OCR_OIL.png')
