from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

EVENT_SHOP_SCROLL_AREA = Button(area=(1064, 201, 1065, 623), color=(130, 130, 141), button=(1064, 201, 1065, 623), file='./assets/cn/shop_event/EVENT_SHOP_SCROLL_AREA.png')
NO_NAV_EVENT_CHECK = Button(area=(20, 545, 46, 571), color=(148, 184, 201), button=(20, 545, 46, 571), file='./assets/cn/shop_event/NO_NAV_EVENT_CHECK.png')
SHOP_EVENT_20240521 = Button(area=(1120, 170, 1169, 221), color=(191, 176, 181), button=(1120, 170, 1169, 221), file='./assets/cn/shop_event/SHOP_EVENT_20240521.png')
SHOP_EVENT_DEADLINE = Button(area=(217, 161, 751, 186), color=(255, 255, 255), button=(217, 161, 751, 186), file='./assets/cn/shop_event/SHOP_EVENT_DEADLINE.png')
SHOP_OCR_BALANCE_SECOND = Button(area=(845, 164, 927, 189), color=(255, 255, 255), button=(845, 164, 927, 189), file='./assets/cn/shop_event/SHOP_OCR_BALANCE_SECOND.png')
TEMPLATE_COST_PRICE_BACKGROUND = Template(file='./assets/cn/shop_event/TEMPLATE_COST_PRICE_BACKGROUND.png')
