from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

SHOP_EVENT_DEADLINE = Button(area={'cn': (191, 165, 617, 183), 'en': (191, 165, 617, 183), 'jp': (191, 165, 617, 183), 'tw': (191, 165, 617, 183)}, color={'cn': (255, 255, 255), 'en': (255, 255, 255), 'jp': (255, 255, 255), 'tw': (255, 255, 255)}, button={'cn': (191, 165, 617, 183), 'en': (191, 165, 617, 183), 'jp': (191, 165, 617, 183), 'tw': (191, 165, 617, 183)}, file={'cn': './assets/cn/shop_event/SHOP_EVENT_DEADLINE.png', 'en': './assets/cn/shop_event/SHOP_EVENT_DEADLINE.png', 'jp': './assets/cn/shop_event/SHOP_EVENT_DEADLINE.png', 'tw': './assets/cn/shop_event/SHOP_EVENT_DEADLINE.png'})
SHOP_OCR_BALANCE_SECOND = Button(area={'cn': (784, 166, 857, 187), 'en': (784, 166, 857, 187), 'jp': (784, 166, 857, 187), 'tw': (784, 166, 857, 187)}, color={'cn': (255, 255, 255), 'en': (255, 255, 255), 'jp': (255, 255, 255), 'tw': (255, 255, 255)}, button={'cn': (784, 166, 857, 187), 'en': (784, 166, 857, 187), 'jp': (784, 166, 857, 187), 'tw': (784, 166, 857, 187)}, file={'cn': './assets/cn/shop_event/SHOP_OCR_BALANCE_SECOND.png', 'en': './assets/cn/shop_event/SHOP_OCR_BALANCE_SECOND.png', 'jp': './assets/cn/shop_event/SHOP_OCR_BALANCE_SECOND.png', 'tw': './assets/cn/shop_event/SHOP_OCR_BALANCE_SECOND.png'})
TEMPLATE_COST_PRICE_BACKGROUND = Template(file={'cn': './assets/cn/shop_event/TEMPLATE_COST_PRICE_BACKGROUND.png', 'en': './assets/cn/shop_event/TEMPLATE_COST_PRICE_BACKGROUND.png', 'jp': './assets/cn/shop_event/TEMPLATE_COST_PRICE_BACKGROUND.png', 'tw': './assets/cn/shop_event/TEMPLATE_COST_PRICE_BACKGROUND.png'})
TEMPLATE_UNOBTAINED = Template(file={'cn': './assets/cn/shop_event/TEMPLATE_UNOBTAINED.png', 'en': './assets/en/shop_event/TEMPLATE_UNOBTAINED.png', 'jp': './assets/jp/shop_event/TEMPLATE_UNOBTAINED.png', 'tw': './assets/cn/shop_event/TEMPLATE_UNOBTAINED.png'})
