from module.base.button import Button
from module.base.template import Template

# This file is generated by module.dev_tools.asset_extract.
# Don't modified it manually.

AMBUSH_AVOID = Button(area={'cn': (753, 444, 927, 502), 'en': (753, 444, 927, 502)}, color={'cn': (87, 129, 189), 'en': (87, 129, 189)}, button={'cn': (979, 444, 1152, 502), 'en': (979, 444, 1152, 502)}, file={'cn': './assets/cn/daemon/AMBUSH_AVOID.png', 'en': './assets/en/daemon/AMBUSH_AVOID.png'})
AT_SEA = Button(area={'cn': (749, 654, 921, 707), 'en': (748, 652, 922, 702)}, color={'cn': (213, 124, 124), 'en': (211, 124, 124)}, button={'cn': (749, 654, 921, 707), 'en': (748, 652, 922, 702)}, file={'cn': './assets/cn/daemon/AT_SEA.png', 'en': './assets/en/daemon/AT_SEA.png'})
FLEET_PREPARATION = Button(area={'cn': (981, 575, 1180, 636), 'en': (978, 572, 1179, 635)}, color={'cn': (235, 185, 114), 'en': (234, 177, 90)}, button={'cn': (981, 575, 1180, 636), 'en': (978, 572, 1179, 635)}, file={'cn': './assets/cn/daemon/FLEET_PREPARATION.png', 'en': './assets/en/daemon/FLEET_PREPARATION.png'})
GET_EMERGENCY_REPAIR = Button(area={'cn': (645, 352, 666, 360), 'en': (645, 352, 666, 360)}, color={'cn': (255, 255, 255), 'en': (255, 255, 255)}, button={'cn': (645, 352, 666, 360), 'en': (645, 352, 666, 360)}, file={'cn': './assets/cn/daemon/GET_EMERGENCY_REPAIR.png', 'en': './assets/en/daemon/GET_EMERGENCY_REPAIR.png'})
GET_ITEMS = Button(area={'cn': (538, 217, 741, 253), 'en': (550, 215, 739, 246)}, color={'cn': (160, 192, 248), 'en': (157, 187, 233)}, button={'cn': (1120, 643, 1146, 666), 'en': (1120, 643, 1146, 666)}, file={'cn': './assets/cn/daemon/GET_ITEMS.png', 'en': './assets/en/daemon/GET_ITEMS.png'})
MAP_PREPARATION = Button(area={'cn': (853, 488, 1053, 549), 'en': (852, 489, 1054, 553)}, color={'cn': (235, 186, 114), 'en': (234, 179, 93)}, button={'cn': (853, 488, 1053, 549), 'en': (852, 489, 1054, 553)}, file={'cn': './assets/cn/daemon/MAP_PREPARATION.png', 'en': './assets/en/daemon/MAP_PREPARATION.png'})
STRATEGY_OPEN = Button(area={'cn': (1102, 480, 1178, 482), 'en': (1102, 480, 1178, 482)}, color={'cn': (255, 223, 74), 'en': (255, 223, 74)}, button={'cn': (1064, 405, 1093, 483), 'en': (1064, 405, 1093, 483)}, file={'cn': './assets/cn/daemon/STRATEGY_OPEN.png', 'en': './assets/en/daemon/STRATEGY_OPEN.png'})
