from module.base.button import Button
from module.base.template import Template

# This file is generated by module.dev_tools.asset_extract.
# Don't modified it manually.

AMBUSH_AVOID = Button(area=(753, 444, 927, 502), color=(87, 129, 189), button=(979, 444, 1152, 502), file='./assets/daemon/AMBUSH_AVOID.png')
AT_SEA = Button(area=(749, 654, 921, 707), color=(213, 124, 124), button=(749, 654, 921, 707), file='./assets/daemon/AT_SEA.png')
FLEET_PREPARATION = Button(area=(981, 575, 1180, 636), color=(235, 185, 114), button=(981, 575, 1180, 636), file='./assets/daemon/FLEET_PREPARATION.png')
GET_EMERGENCY_REPAIR = Button(area=(645, 352, 666, 360), color=(255, 255, 255), button=(645, 352, 666, 360), file='./assets/daemon/GET_EMERGENCY_REPAIR.png')
GET_ITEMS = Button(area=(538, 217, 741, 253), color=(160, 192, 248), button=(1120, 643, 1146, 666), file='./assets/daemon/GET_ITEMS.png')
MAP_PREPARATION = Button(area=(853, 488, 1053, 549), color=(235, 186, 114), button=(853, 488, 1053, 549), file='./assets/daemon/MAP_PREPARATION.png')
STRATEGY_OPEN = Button(area=(1102, 480, 1178, 482), color=(255, 223, 74), button=(1064, 405, 1093, 483), file='./assets/daemon/STRATEGY_OPEN.png')
