import datetime

# This file was automatically generated by module/config/config_updater.py.
# Don't modify it manually.


class GeneratedConfig:
    """
    Auto generated configuration
    """

    # Group `Scheduler`
    Scheduler_Enable = False
    Scheduler_NextRun = datetime.datetime(2020, 1, 1, 0, 0)
    Scheduler_Command = 'Maa'
    Scheduler_SuccessInterval = 60
    Scheduler_FailureInterval = 120
    Scheduler_ServerUpdate = '04:00'

    # Group `Emulator`
    Emulator_Serial = '127.0.0.1:5555'
    Emulator_PackageName = 'Official'  # Official, Bilibili
    Emulator_Server = 'CN'  # CN, US, JP, KR
    Emulator_MaaPath = 'D:/Program Files/MAA'
    Emulator_ServerName = 'disabled'

    # Group `Record`
    Record_ReportToPenguin = False
    Record_PenguinID = None

    # Group `Error`
    Error_SaveError = False
    Error_OnePushConfig = 'provider: null'

    # Group `Optimization`
    Optimization_WhenTaskQueueEmpty = 'stay_there'

    # Group `Fight`
    Fight_Stage = '1-7'
    Fight_Medicine = 0
    Fight_Stone = 0
    Fight_Times = 0
    Fight_Drops = None
    Fight_DrGrandet = False

    # Group `Recruit`
    Recruit_Refresh = True
    Recruit_SkipRobot = True
    Recruit_Select3 = True
    Recruit_Select4 = True
    Recruit_Select5 = True
    Recruit_Times = 4
    Recruit_Expedite = False

    # Group `Infrast`
    Infrast_Facility = 'Mfg > Trade > Power > Control > Reception > Office > Dorm'
    Infrast_Drones = 'Money'  # _NotUse, Money, SyntheticJade, CombatRecord, PureGold, OriginStone, Chip
    Infrast_Threshold = 0.3
    Infrast_Replenish = False

    # Group `Mall`
    Mall_Shopping = True
    Mall_BuyFirst = '招聘许可 > 龙门币'
    Mall_BlackList = '碳 > 家具'

    # Group `Roguelike`
    Roguelike_Mode = 0  # 0, 1
    Roguelike_StartsCount = 9999999
    Roguelike_InvestmentsCount = 9999999
    Roguelike_StopWhenInvestmentFull = False
    Roguelike_Squad = '指挥分队'  # 指挥分队, 集群分队, 后勤分队, 矛头分队, 突击战术分队, 堡垒战术分队, 远程战术分队, 破坏战术分队, 研究分队, 高规格分队
    Roguelike_Roles = '取长补短'  # 先手必胜, 稳扎稳打, 取长补短, 随心所欲
    Roguelike_CoreChar = None

    # Group `Copilot`
    Copilot_FileName = None
    Copilot_Formation = False
