from module.base.button import Button
from module.base.template import Template

# This file is generated by module.dev_tools.asset_extract.
# Don't modified it manually.

AUTOMATION_CONFIRM = Button(area=(553, 526, 727, 584), color=(98, 146, 206), button=(553, 526, 727, 584), file='./assets/combat/AUTOMATION_CONFIRM.png')
AUTOMATION_CONFIRM_CHECK = Button(area=(745, 423, 764, 439), color=(181, 85, 82), button=(745, 423, 764, 439), file='./assets/combat/AUTOMATION_CONFIRM_CHECK.png')
AUTOMATION_OFF = Button(area=(754, 113, 794, 129), color=(119, 71, 70), button=(754, 113, 794, 129), file='./assets/combat/AUTOMATION_OFF.png')
AUTOMATION_ON = Button(area=(759, 113, 790, 129), color=(22, 112, 81), button=(759, 113, 790, 129), file='./assets/combat/AUTOMATION_ON.png')
AUTOMATION_SWITCH = Button(area=(821, 106, 907, 136), color=(95, 109, 147), button=(821, 106, 907, 136), file='./assets/combat/AUTOMATION_SWITCH.png')
BATTLE_PREPARATION = Button(area=(1043, 607, 1241, 667), color=(234, 179, 97), button=(1043, 607, 1241, 667), file='./assets/combat/BATTLE_PREPARATION.png')
BATTLE_PREPARATION_WITH_OVERLAY = Button(area=(1058, 622, 1226, 652), color=(96, 74, 39), button=(1058, 622, 1226, 652), file='./assets/combat/BATTLE_PREPARATION_WITH_OVERLAY.png')
BATTLE_STATUS_A = Button(area=(622, 266, 732, 288), color=(235, 227, 111), button=(1000, 631, 1055, 689), file='./assets/combat/BATTLE_STATUS_A.png')
BATTLE_STATUS_S = Button(area=(633, 297, 722, 320), color=(233, 241, 127), button=(1000, 631, 1055, 689), file='./assets/combat/BATTLE_STATUS_S.png')
COMBAT_AUTO = Button(area=(136, 573, 167, 604), color=(229, 242, 255), button=(136, 573, 167, 604), file='./assets/combat/COMBAT_AUTO.png')
COMBAT_AUTO_SWITCH = Button(area=(18, 38, 36, 56), color=(179, 198, 235), button=(18, 38, 36, 56), file='./assets/combat/COMBAT_AUTO_SWITCH.png')
EXP_INFO_A = Button(area=(389, 100, 444, 116), color=(236, 231, 116), button=(1000, 631, 1055, 689), file='./assets/combat/EXP_INFO_A.png')
EXP_INFO_S = Button(area=(396, 122, 457, 137), color=(233, 241, 127), button=(1000, 631, 1055, 689), file='./assets/combat/EXP_INFO_S.png')
GET_ITEMS_1 = Button(area=(538, 217, 741, 253), color=(160, 192, 248), button=(1000, 631, 1055, 689), file='./assets/combat/GET_ITEMS_1.png')
GET_ITEMS_2 = Button(area=(538, 146, 742, 182), color=(160, 192, 248), button=(1000, 631, 1055, 689), file='./assets/combat/GET_ITEMS_2.png')
GET_SHIP = Button(area=(1104, 610, 1110, 630), color=(255, 255, 255), button=(1000, 631, 1055, 689), file='./assets/combat/GET_SHIP.png')
LOADING_BAR = Button(area=(33, 676, 1247, 680), color=(172, 205, 232), button=(33, 676, 1247, 680), file='./assets/combat/LOADING_BAR.png')
MOVE_DOWN = Button(area=(148, 647, 155, 669), color=(21, 28, 57), button=(148, 647, 155, 669), file='./assets/combat/MOVE_DOWN.png')
PAUSE = Button(area=(1236, 37, 1244, 59), color=(247, 243, 247), button=(1162, 34, 1246, 61), file='./assets/combat/PAUSE.png')
PAUSE_DOUBLE_CHECK = Button(area=(1231, 35, 1236, 60), color=(96, 104, 136), button=(1231, 35, 1236, 60), file='./assets/combat/PAUSE_DOUBLE_CHECK.png')
SUBMARINE_AVAILABLE_CHECK_1 = Button(area=(707, 660, 712, 665), color=(255, 255, 255), button=(707, 660, 712, 665), file='./assets/combat/SUBMARINE_AVAILABLE_CHECK_1.png')
SUBMARINE_AVAILABLE_CHECK_2 = Button(area=(790, 631, 795, 641), color=(255, 255, 255), button=(790, 631, 795, 641), file='./assets/combat/SUBMARINE_AVAILABLE_CHECK_2.png')
SUBMARINE_CALLED = Button(area=(737, 608, 750, 626), color=(132, 134, 132), button=(737, 608, 750, 626), file='./assets/combat/SUBMARINE_CALLED.png')
SUBMARINE_READY = Button(area=(737, 608, 752, 625), color=(255, 251, 255), button=(737, 608, 752, 625), file='./assets/combat/SUBMARINE_READY.png')
