from module.base.button import Button
from module.base.template import Template

# This file is generated by module.dev_tools.asset_extract.
# Don't modified it manually.

GET_AMMO = Button(area=(792, 315, 794, 333), color=(251, 250, 255), button=(792, 315, 794, 333), file='./assets/handler/GET_AMMO.png')
GET_ITEMS_1 = Button(area=(538, 217, 741, 253), color=(160, 192, 248), button=(924, 653, 943, 672), file='./assets/handler/GET_ITEMS_1.png')
GET_MISSION = Button(area=(553, 491, 727, 551), color=(96, 144, 204), button=(553, 491, 727, 551), file='./assets/handler/GET_MISSION.png')
INFO_BAR_1 = Button(area=(194, 297, 1086, 299), color=(107, 158, 255), button=(194, 297, 1086, 299), file='./assets/handler/INFO_BAR_1.png')
INFO_BAR_2 = Button(area=(194, 234, 1086, 236), color=(107, 158, 255), button=(194, 234, 1086, 236), file='./assets/handler/INFO_BAR_2.png')
INFO_BAR_3 = Button(area=(194, 171, 1086, 173), color=(107, 158, 255), button=(194, 171, 1086, 173), file='./assets/handler/INFO_BAR_3.png')
IN_MAP = Button(area=(749, 654, 921, 707), color=(213, 124, 124), button=(749, 654, 921, 707), file='./assets/handler/IN_MAP.png')
IN_STAGE_BLUE = Button(area=(20, 641, 148, 702), color=(154, 177, 226), button=(20, 641, 148, 702), file='./assets/handler/IN_STAGE_BLUE.png')
IN_STAGE_RED = Button(area=(22, 643, 150, 704), color=(229, 159, 159), button=(22, 643, 150, 704), file='./assets/handler/IN_STAGE_RED.png')
MAP_AIR_RAID = Button(area=(350, 447, 1280, 472), color=(154, 43, 46), button=(350, 447, 1280, 472), file='./assets/handler/MAP_AIR_RAID.png')
MAP_AMBUSH = Button(area=(261, 433, 1280, 449), color=(161, 41, 43), button=(261, 433, 1280, 449), file='./assets/handler/MAP_AMBUSH.png')
MAP_AMBUSH_EVADE = Button(area=(325, 393, 1280, 395), color=(255, 255, 255), button=(979, 444, 1152, 502), file='./assets/handler/MAP_AMBUSH_EVADE.png')
MAP_ENEMY_SEARCHING = Button(area=(531, 320, 864, 382), color=(200, 99, 91), button=(531, 320, 864, 382), file='./assets/handler/MAP_ENEMY_SEARCHING.png')
MYSTERY_ITEM = Button(area=(589, 294, 691, 427), color=(144, 127, 83), button=(589, 294, 691, 427), file='./assets/handler/MYSTERY_ITEM.png')
STRATEGY_OPEN_1 = Button(area=(1176, 366, 1275, 393), color=(128, 155, 218), button=(1060, 406, 1092, 485), file='./assets/handler/STRATEGY_OPEN_1.png')
