from .classes import MapPlane

# This file was auto-generated, do not modify it manually. To generate:
# ``` python -m dev_tools.keyword_extract ```

Special_HertaOffice = MapPlane(
    id=1,
    name='Special_HertaOffice',
    cn='黑塔的办公室',
    cht='黑塔的辦公室',
    en="Herta's Office",
    jp='ヘルタのオフィス',
    es='Oficina de Herta',
    world_id=-1,
    plane_id=1,
)
Special_AptitudeShowcase = MapPlane(
    id=2,
    name='Special_AptitudeShowcase',
    cn='锋芒崭露',
    cht='鋒芒嶄露',
    en='Aptitude Showcase',
    jp='躍進する新星',
    es='Demostración de aptitudes',
    world_id=-1,
    plane_id=2,
)
Rogue_DomainCombat = MapPlane(
    id=3,
    name='Rogue_DomainCombat',
    cn='区域-战斗',
    cht='區域-戰鬥',
    en='Domain — Combat',
    jp='エリア-戦闘',
    es='Batalla',
    world_id=-2,
    plane_id=1,
)
Rogue_DomainOccurrence = MapPlane(
    id=4,
    name='Rogue_DomainOccurrence',
    cn='区域-事件',
    cht='區域-事件',
    en='Domain — Occurrence',
    jp='エリア-イベント',
    es='Evento',
    world_id=-2,
    plane_id=2,
)
Rogue_DomainEncounter = MapPlane(
    id=5,
    name='Rogue_DomainEncounter',
    cn='区域-遭遇',
    cht='區域-遭遇',
    en='Domain — Encounter',
    jp='エリア-遭遇',
    es='Encuentro',
    world_id=-2,
    plane_id=3,
)
Rogue_DomainRespite = MapPlane(
    id=6,
    name='Rogue_DomainRespite',
    cn='区域-休整',
    cht='區域-整備',
    en='Domain — Respite',
    jp='エリア-休憩',
    es='Reposo',
    world_id=-2,
    plane_id=4,
)
Rogue_DomainElite = MapPlane(
    id=7,
    name='Rogue_DomainElite',
    cn='区域-精英',
    cht='區域-菁英',
    en='Domain — Elite',
    jp='エリア-精鋭',
    es='Élite',
    world_id=-2,
    plane_id=5,
)
Rogue_DomainBoss = MapPlane(
    id=8,
    name='Rogue_DomainBoss',
    cn='区域-首领',
    cht='區域-頭目',
    en='Domain — Boss',
    jp='エリア-ボス',
    es='Jefe',
    world_id=-2,
    plane_id=6,
)
Rogue_DomainTransaction = MapPlane(
    id=9,
    name='Rogue_DomainTransaction',
    cn='区域-交易',
    cht='區域-交易',
    en='Domain — Transaction',
    jp='エリア-取引',
    es='Transacción',
    world_id=-2,
    plane_id=7,
)
Herta_ParlorCar = MapPlane(
    id=10,
    name='Herta_ParlorCar',
    cn='观景车厢',
    cht='觀景車廂',
    en='Parlor Car',
    jp='列車のラウンジ',
    es='Vagón panorámico',
    world_id=0,
    plane_id=1000001,
)
Herta_MasterControlZone = MapPlane(
    id=11,
    name='Herta_MasterControlZone',
    cn='主控舱段',
    cht='主控艙段',
    en='Master Control Zone',
    jp='主制御部分',
    es='Zona de mando principal',
    world_id=0,
    plane_id=1000101,
)
Herta_BaseZone = MapPlane(
    id=12,
    name='Herta_BaseZone',
    cn='基座舱段',
    cht='基座艙段',
    en='Base Zone',
    jp='ベース部分',
    es='Zona de la base',
    world_id=0,
    plane_id=2000101,
)
Herta_StorageZone = MapPlane(
    id=13,
    name='Herta_StorageZone',
    cn='收容舱段',
    cht='收容艙段',
    en='Storage Zone',
    jp='収容部分',
    es='Zona de almacenamiento',
    world_id=0,
    plane_id=2000201,
)
Herta_SupplyZone = MapPlane(
    id=14,
    name='Herta_SupplyZone',
    cn='支援舱段',
    cht='支援艙段',
    en='Supply Zone',
    jp='サポート部分',
    es='Zona de suministros',
    world_id=0,
    plane_id=2000301,
)
Herta_SeclusionZone = MapPlane(
    id=15,
    name='Herta_SeclusionZone',
    cn='禁闭舱段',
    cht='禁閉艙段',
    en='Seclusion Zone',
    jp='封鎖部分',
    es='Zona de confinamiento',
    world_id=0,
    plane_id=2000401,
)
Jarilo_AdministrativeDistrict = MapPlane(
    id=16,
    name='Jarilo_AdministrativeDistrict',
    cn='行政区',
    cht='行政區',
    en='Administrative District',
    jp='行政区',
    es='Distrito administrativo',
    world_id=1,
    plane_id=1010101,
)
Jarilo_OutlyingSnowPlains = MapPlane(
    id=17,
    name='Jarilo_OutlyingSnowPlains',
    cn='城郊雪原',
    cht='城郊雪原',
    en='Outlying Snow Plains',
    jp='郊外雪原',
    es='Llanuras nevadas de las afueras',
    world_id=1,
    plane_id=2010101,
)
Jarilo_BackwaterPass = MapPlane(
    id=18,
    name='Jarilo_BackwaterPass',
    cn='边缘通路',
    cht='邊緣通道',
    en='Backwater Pass',
    jp='外縁通路',
    es='Paso del Remanso',
    world_id=1,
    plane_id=2011101,
)
Jarilo_SilvermaneGuardRestrictedZone = MapPlane(
    id=19,
    name='Jarilo_SilvermaneGuardRestrictedZone',
    cn='铁卫禁区',
    cht='鐵衛禁區',
    en='Silvermane Guard Restricted Zone',
    jp='シルバーメイン禁区',
    es='Zona restringida de la Guardia Crinargenta',
    world_id=1,
    plane_id=2013101,
)
Jarilo_CorridorofFadingEchoes = MapPlane(
    id=20,
    name='Jarilo_CorridorofFadingEchoes',
    cn='残响回廊',
    cht='殘響迴廊',
    en='Corridor of Fading Echoes',
    jp='残響回廊',
    es='Pasadizo de los ecos apagados',
    world_id=1,
    plane_id=2013201,
)
Jarilo_EverwinterHill = MapPlane(
    id=21,
    name='Jarilo_EverwinterHill',
    cn='永冬岭',
    cht='永冬嶺',
    en='Everwinter Hill',
    jp='常冬峰',
    es='Colina del Siempreinvierno',
    world_id=1,
    plane_id=2013401,
)
Jarilo_PillarsofCreation = MapPlane(
    id=22,
    name='Jarilo_PillarsofCreation',
    cn='造物之柱',
    cht='造物之柱',
    en='Pillars of Creation',
    jp='造物の柱',
    es='Pilares de la Creación',
    world_id=1,
    plane_id=2013501,
)
Jarilo_OldWeaponTestingGround = MapPlane(
    id=23,
    name='Jarilo_OldWeaponTestingGround',
    cn='旧武器试验场',
    cht='舊武器試驗場',
    en='Old Weapon Testing Ground',
    jp='旧武器実験場',
    es='Antiguo campo de prueba de armas',
    world_id=1,
    plane_id=2013601,
)
Jarilo_BoulderTown = MapPlane(
    id=24,
    name='Jarilo_BoulderTown',
    cn='磐岩镇',
    cht='磐岩鎮',
    en='Boulder Town',
    jp='ボルダータウン',
    es='Villarroca',
    world_id=1,
    plane_id=1010201,
)
Jarilo_GreatMine = MapPlane(
    id=25,
    name='Jarilo_GreatMine',
    cn='大矿区',
    cht='大礦區',
    en='Great Mine',
    jp='大鉱区',
    es='Mina principal',
    world_id=1,
    plane_id=2012101,
)
Jarilo_RivetTown = MapPlane(
    id=26,
    name='Jarilo_RivetTown',
    cn='铆钉镇',
    cht='鉚釘鎮',
    en='Rivet Town',
    jp='リベットタウン',
    es='Villarremache',
    world_id=1,
    plane_id=2012201,
)
Jarilo_RobotSettlement = MapPlane(
    id=27,
    name='Jarilo_RobotSettlement',
    cn='机械聚落',
    cht='機械聚落',
    en='Robot Settlement',
    jp='機械集落',
    es='Asentamiento robot',
    world_id=1,
    plane_id=2012301,
)
Luofu_CentralStarskiffHaven = MapPlane(
    id=28,
    name='Luofu_CentralStarskiffHaven',
    cn='星槎海中枢',
    cht='星槎海中樞',
    en='Central Starskiff Haven',
    jp='星槎海中枢',
    es='Zona central de la Dársena de astroesquifes',
    world_id=2,
    plane_id=1020101,
)
Luofu_Cloudford = MapPlane(
    id=29,
    name='Luofu_Cloudford',
    cn='流云渡',
    cht='流雲渡',
    en='Cloudford',
    jp='流雲渡し',
    es='Vado de las Nubes',
    world_id=2,
    plane_id=2021101,
)
Luofu_StargazerNavalia = MapPlane(
    id=30,
    name='Luofu_StargazerNavalia',
    cn='迴星港',
    cht='迴星港',
    en='Stargazer Navalia',
    jp='廻星港',
    es='Puerto Miraestrellas',
    world_id=2,
    plane_id=2021201,
)
Luofu_ExaltingSanctum = MapPlane(
    id=31,
    name='Luofu_ExaltingSanctum',
    cn='长乐天',
    cht='長樂天',
    en='Exalting Sanctum',
    jp='長楽天',
    es='Sánctum de la Exaltación',
    world_id=2,
    plane_id=1020201,
)
Luofu_AurumAlley = MapPlane(
    id=32,
    name='Luofu_AurumAlley',
    cn='金人巷',
    cht='金人巷',
    en='Aurum Alley',
    jp='金人巷',
    es='Callejón Aurum',
    world_id=2,
    plane_id=1020204,
)
Luofu_DivinationCommission = MapPlane(
    id=33,
    name='Luofu_DivinationCommission',
    cn='太卜司',
    cht='太卜司',
    en='Divination Commission',
    jp='太卜司',
    es='Comisión de Adivinación',
    world_id=2,
    plane_id=2022101,
)
Luofu_ArtisanshipCommission = MapPlane(
    id=34,
    name='Luofu_ArtisanshipCommission',
    cn='工造司',
    cht='工造司',
    en='Artisanship Commission',
    jp='工造司',
    es='Comisión de Artesanía',
    world_id=2,
    plane_id=2022201,
)
Luofu_FyxestrollGarden = MapPlane(
    id=35,
    name='Luofu_FyxestrollGarden',
    cn='绥园',
    cht='綏園',
    en='Fyxestroll Garden',
    jp='綏園',
    es='Jardín del Sosiego',
    world_id=2,
    plane_id=2022301,
)
Luofu_AlchemyCommission = MapPlane(
    id=36,
    name='Luofu_AlchemyCommission',
    cn='丹鼎司',
    cht='丹鼎司',
    en='Alchemy Commission',
    jp='丹鼎司',
    es='Comisión de Alquimia',
    world_id=2,
    plane_id=2023101,
)
Luofu_ScalegorgeWaterscape = MapPlane(
    id=37,
    name='Luofu_ScalegorgeWaterscape',
    cn='鳞渊境',
    cht='鱗淵境',
    en='Scalegorge Waterscape',
    jp='鱗淵境',
    es='Desfiladero de Escamas',
    world_id=2,
    plane_id=2023201,
)
Penacony_TheReverieReality = MapPlane(
    id=38,
    name='Penacony_TheReverieReality',
    cn='「白日梦」酒店-现实',
    cht='「白日夢」飯店-現實',
    en='The Reverie (Reality)',
    jp='ホテル・レバリー-現実',
    es='Hotel Fantasía (realidad)',
    world_id=3,
    plane_id=1030501,
)
Penacony_GoldenHour = MapPlane(
    id=39,
    name='Penacony_GoldenHour',
    cn='黄金的时刻',
    cht='黃金的時刻',
    en='Golden Hour',
    jp='黄金の刻',
    es='Momento Dorado',
    world_id=3,
    plane_id=1030101,
)
Penacony_DreamEdge = MapPlane(
    id=40,
    name='Penacony_DreamEdge',
    cn='筑梦边境',
    cht='築夢邊境',
    en="Dream's Edge",
    jp='ドリームボーダー',
    es='Frontera de los Sueños',
    world_id=3,
    plane_id=2031301,
)
Penacony_AChildDream = MapPlane(
    id=41,
    name='Penacony_AChildDream',
    cn='稚子的梦',
    cht='稚子的夢',
    en="A Child's Dream",
    jp='稚児の夢',
    es='Sueño infantil',
    world_id=3,
    plane_id=2031201,
)
Penacony_TheReverieDreamscape = MapPlane(
    id=42,
    name='Penacony_TheReverieDreamscape',
    cn='「白日梦」酒店-梦境',
    cht='「白日夢」飯店-夢境',
    en='The Reverie (Dreamscape)',
    jp='ホテル・レバリー-夢境',
    es='Hotel Fantasía (paisaje onírico)',
    world_id=3,
    plane_id=2031101,
)
