from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools.button_extract.
# Don't modify it manually.

TEST = Button(area={'cn': (126, 57, 1232, 650), 'en': (126, 57, 1232, 650), 'jp': (126, 57, 1232, 650)}, color={'cn': (255, 255, 255), 'en': (255, 255, 255), 'jp': (255, 255, 255)}, button={'cn': (126, 57, 1232, 650), 'en': (126, 57, 1232, 650), 'jp': (126, 57, 1232, 650)}, file={'cn': './assets/cn/decomposition/TEST.png', 'en': './assets/cn/decomposition/TEST.png', 'jp': './assets/cn/decomposition/TEST.png'})
WAREHOUSE_OPEN = Button(area={'cn': (328, 667, 484, 713), 'en': (328, 667, 484, 713), 'jp': (328, 667, 484, 713)}, color={'cn': (93, 111, 143), 'en': (93, 111, 143), 'jp': (93, 111, 143)}, button={'cn': (328, 667, 484, 713), 'en': (328, 667, 484, 713), 'jp': (328, 667, 484, 713)}, file={'cn': './assets/cn/decomposition/WAREHOUSE_OPEN.png', 'en': './assets/cn/decomposition/WAREHOUSE_OPEN.png', 'jp': './assets/cn/decomposition/WAREHOUSE_OPEN.png'})
