from module.base.button import Button
from module.base.template import Template

# This file is generated by module.dev_tools.asset_extract.
# Don't modified it manually.

EQUIP_CONFIRM = Button(area=(871, 516, 1044, 573), color=(95, 143, 203), button=(871, 516, 1044, 573), file='./assets/retire/EQUIP_CONFIRM.png')
EQUIP_CONFIRM_2 = Button(area=(720, 541, 893, 598), color=(94, 142, 202), button=(720, 541, 893, 598), file='./assets/retire/EQUIP_CONFIRM_2.png')
GET_ITEMS_1_RETIREMENT_SAVE = Button(area=(951, 654, 987, 687), color=(64, 62, 69), button=(951, 654, 987, 687), file='./assets/retire/GET_ITEMS_1_RETIREMENT_SAVE.png')
IN_RETIREMENT_CHECK = Button(area=(854, 641, 1027, 698), color=(184, 99, 89), button=(854, 641, 1027, 698), file='./assets/retire/IN_RETIREMENT_CHECK.png')
RETIRE_APPEAR_1 = Button(area=(353, 492, 527, 550), color=(96, 144, 204), button=(353, 492, 527, 550), file='./assets/retire/RETIRE_APPEAR_1.png')
RETIRE_APPEAR_2 = Button(area=(553, 492, 727, 550), color=(94, 143, 204), button=(553, 492, 727, 550), file='./assets/retire/RETIRE_APPEAR_2.png')
RETIRE_APPEAR_3 = Button(area=(753, 492, 927, 550), color=(94, 143, 202), button=(753, 492, 927, 550), file='./assets/retire/RETIRE_APPEAR_3.png')
SHIP_CONFIRM = Button(area=(1069, 641, 1241, 698), color=(84, 131, 190), button=(1069, 641, 1241, 698), file='./assets/retire/SHIP_CONFIRM.png')
SHIP_CONFIRM_2 = Button(area=(928, 617, 1100, 674), color=(95, 143, 203), button=(928, 617, 1100, 674), file='./assets/retire/SHIP_CONFIRM_2.png')
SORTNG_CLICK = Button(area=(1004, 14, 1096, 42), color=(49, 54, 67), button=(1004, 14, 1096, 42), file='./assets/retire/SORTNG_CLICK.png')
SORT_ASC = Button(area=(1014, 22, 1019, 26), color=(189, 207, 231), button=(1014, 22, 1019, 26), file='./assets/retire/SORT_ASC.png')
SORT_DESC = Button(area=(1014, 29, 1019, 33), color=(189, 207, 231), button=(1014, 29, 1019, 33), file='./assets/retire/SORT_DESC.png')
