/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Alas: typeof import('./src/components/Alas.vue')['default']
    AlasTitle: typeof import('./src/components/AlasTitle.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    CountTo: typeof import('./src/components/CountTo.vue')['default']
    ProgressBar: typeof import('./src/components/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spin: typeof import('./src/components/Spin.vue')['default']
  }
}
