class Campaign(CampaignBase):
    def battle_0(self):
        if self.fleet_2_protect():
            return True
        if self.clear_siren():
            return True
        return self.battle_default()
    def battle_5(self):
        return self.fleet_boss.clear_boss()
