from module.base.button import Button
from module.base.template import Template

# This file is generated by module.dev_tools.asset_extract.
# Don't modified it manually.

EQUIP_ENTER_1 = Button(area=(712, 163, 782, 233), color=(59, 63, 66), button=(712, 163, 782, 233), file='./assets/hard/EQUIP_ENTER_1.png')
EQUIP_ENTER_2 = Button(area=(713, 296, 783, 366), color=(60, 63, 63), button=(713, 296, 783, 366), file='./assets/hard/EQUIP_ENTER_2.png')
OCR_HARD_REMAIN = Button(area=(98, 612, 109, 628), color=(79, 141, 42), button=(98, 612, 109, 628), file='./assets/hard/OCR_HARD_REMAIN.png')
