from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

EQUIP_ENTER_1 = Button(
    area={
        "cn": (712, 163, 782, 233),
        "en": (712, 163, 782, 233),
        "jp": (712, 163, 782, 233),
        "tw": (712, 163, 782, 233),
    },
    color={
        "cn": (59, 63, 66),
        "en": (59, 63, 66),
        "jp": (59, 63, 66),
        "tw": (59, 63, 66),
    },
    button={
        "cn": (712, 163, 782, 233),
        "en": (712, 163, 782, 233),
        "jp": (712, 163, 782, 233),
        "tw": (712, 163, 782, 233),
    },
    file={
        "cn": "./assets/cn/hard/EQUIP_ENTER_1.png",
        "en": "./assets/en/hard/EQUIP_ENTER_1.png",
        "jp": "./assets/jp/hard/EQUIP_ENTER_1.png",
        "tw": "./assets/tw/hard/EQUIP_ENTER_1.png",
    },
)
EQUIP_ENTER_2 = Button(
    area={
        "cn": (713, 296, 783, 366),
        "en": (713, 296, 783, 366),
        "jp": (713, 296, 783, 366),
        "tw": (713, 296, 783, 366),
    },
    color={
        "cn": (60, 63, 63),
        "en": (60, 63, 63),
        "jp": (60, 63, 63),
        "tw": (60, 63, 63),
    },
    button={
        "cn": (713, 296, 783, 366),
        "en": (713, 296, 783, 366),
        "jp": (713, 296, 783, 366),
        "tw": (713, 296, 783, 366),
    },
    file={
        "cn": "./assets/cn/hard/EQUIP_ENTER_2.png",
        "en": "./assets/en/hard/EQUIP_ENTER_2.png",
        "jp": "./assets/jp/hard/EQUIP_ENTER_2.png",
        "tw": "./assets/tw/hard/EQUIP_ENTER_2.png",
    },
)
OCR_HARD_REMAIN = Button(
    area={
        "cn": (94, 608, 109, 631),
        "en": (94, 608, 109, 631),
        "jp": (94, 608, 109, 631),
        "tw": (94, 608, 109, 631),
    },
    color={
        "cn": (49, 80, 30),
        "en": (49, 80, 30),
        "jp": (49, 80, 30),
        "tw": (49, 80, 30),
    },
    button={
        "cn": (94, 608, 109, 631),
        "en": (94, 608, 109, 631),
        "jp": (94, 608, 109, 631),
        "tw": (94, 608, 109, 631),
    },
    file={
        "cn": "./assets/cn/hard/OCR_HARD_REMAIN.png",
        "en": "./assets/en/hard/OCR_HARD_REMAIN.png",
        "jp": "./assets/jp/hard/OCR_HARD_REMAIN.png",
        "tw": "./assets/tw/hard/OCR_HARD_REMAIN.png",
    },
)
