from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

EQUIP_ENTER_1 = Button(area=(712, 163, 782, 233), color=(59, 63, 66), button=(712, 163, 782, 233), file={'cn': './assets/cn/hard/EQUIP_ENTER_1.png', 'en': './assets/en/hard/EQUIP_ENTER_1.png', 'jp': './assets/jp/hard/EQUIP_ENTER_1.png', 'tw': './assets/tw/hard/EQUIP_ENTER_1.png'})
EQUIP_ENTER_2 = Button(area=(713, 296, 783, 366), color=(60, 63, 63), button=(713, 296, 783, 366), file={'cn': './assets/cn/hard/EQUIP_ENTER_2.png', 'en': './assets/en/hard/EQUIP_ENTER_2.png', 'jp': './assets/jp/hard/EQUIP_ENTER_2.png', 'tw': './assets/tw/hard/EQUIP_ENTER_2.png'})
OCR_HARD_REMAIN = Button(area=(94, 608, 109, 631), color=(49, 80, 30), button=(94, 608, 109, 631), file={'cn': './assets/cn/hard/OCR_HARD_REMAIN.png', 'en': './assets/en/hard/OCR_HARD_REMAIN.png', 'jp': './assets/jp/hard/OCR_HARD_REMAIN.png', 'tw': './assets/tw/hard/OCR_HARD_REMAIN.png'})
