from tasks.assignment.assets.assets_assignment_ui import (
    CHARACTER_MATERIALS_CHECK, CHARACTER_MATERIALS_CLICK,
    EXP_MATERIALS_CREDITS_CHECK, EXP_MATERIALS_CREDITS_CLICK, GROUP_SEARCH,
    SPACE_STATION_TASK_FORCE_CHECK, SPACE_STATION_TASK_FORCE_CLICK,
    SYNTHESIS_MATERIALS_CHECK, SYNTHESIS_MATERIALS_CLICK
)

for group_button_wrapper in (
    SPACE_STATION_TASK_FORCE_CHECK, SPACE_STATION_TASK_FORCE_CLICK,
    CHARACTER_MATERIALS_CHECK, CHARACTER_MATERIALS_CLICK,
    EXP_MATERIALS_CREDITS_CHECK, EXP_MATERIALS_CREDITS_CLICK,
    SYNTHESIS_MATERIALS_CHECK, SYNTHESIS_MATERIALS_CLICK,
):
    group_button_wrapper.load_search(GROUP_SEARCH.button)
