from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ASIDE_NEXT_PAGE = Button(area=(167, 627, 183, 637), color=(163, 160, 174), button=(167, 627, 183, 637), file='./assets/cn/event_hospital/ASIDE_NEXT_PAGE.png')
CLUE_LIST = Button(area=(98, 156, 247, 616), color=(255, 255, 255), button=(98, 156, 247, 616), file='./assets/cn/event_hospital/CLUE_LIST.png')
DAILY_RED_DOT = Button(area=(1014, 658, 1051, 671), color=(61, 50, 52), button=(1014, 658, 1051, 671), file='./assets/cn/event_hospital/DAILY_RED_DOT.png')
DAILY_REWARD_RECEIVE = Button(area=(874, 620, 1157, 677), color=(46, 57, 90), button=(874, 620, 1157, 677), file='./assets/cn/event_hospital/DAILY_REWARD_RECEIVE.png')
GET_CLUE = Button(area=(617, 80, 653, 106), color=(92, 99, 107), button=(570, 593, 710, 627), file='./assets/cn/event_hospital/GET_CLUE.png')
GET_CLUE_TEXT = Button(area=(607, 105, 651, 126), color=(140, 140, 142), button=(607, 105, 651, 126), file='./assets/cn/event_hospital/GET_CLUE_TEXT.png')
HOSIPITAL_CHECK = Button(area=(37, 26, 74, 60), color=(105, 104, 105), button=(37, 26, 74, 60), file='./assets/cn/event_hospital/HOSIPITAL_CHECK.png')
HOSIPITAL_CLUE_CHECK = Button(area=(1167, 90, 1207, 126), color=(197, 148, 150), button=(1167, 90, 1207, 126), file='./assets/cn/event_hospital/HOSIPITAL_CLUE_CHECK.png')
HOSIPITAL_GOTO_CLUE = Button(area=(1087, 662, 1126, 697), color=(80, 82, 83), button=(1087, 662, 1126, 697), file='./assets/cn/event_hospital/HOSIPITAL_GOTO_CLUE.png')
HOSPITAL_BATTLE_EXIT = Button(area=(1097, 112, 1137, 147), color=(210, 161, 165), button=(1097, 112, 1137, 147), file='./assets/cn/event_hospital/HOSPITAL_BATTLE_EXIT.png')
HOSPITAL_BATTLE_PREPARE = Button(area={'cn': (964, 503, 1028, 532), 'en': (879, 507, 967, 531), 'jp': (965, 504, 1026, 533), 'tw': (963, 503, 1028, 533)}, color={'cn': (115, 113, 118), 'en': (104, 102, 106), 'jp': (121, 119, 125), 'tw': (123, 121, 126)}, button={'cn': (964, 503, 1028, 532), 'en': (879, 507, 967, 531), 'jp': (965, 504, 1026, 533), 'tw': (963, 503, 1028, 533)}, file={'cn': './assets/cn/event_hospital/HOSPITAL_BATTLE_PREPARE.png', 'en': './assets/en/event_hospital/HOSPITAL_BATTLE_PREPARE.png', 'jp': './assets/jp/event_hospital/HOSPITAL_BATTLE_PREPARE.png', 'tw': './assets/tw/event_hospital/HOSPITAL_BATTLE_PREPARE.png'})
HOSPITAL_GOTO_DAILY = Button(area=(900, 658, 928, 688), color=(117, 119, 120), button=(900, 658, 928, 688), file='./assets/cn/event_hospital/HOSPITAL_GOTO_DAILY.png')
INVEST_REWARD_RECEIVE = Button(area=(1113, 666, 1236, 690), color=(97, 99, 117), button=(1113, 666, 1236, 690), file='./assets/cn/event_hospital/INVEST_REWARD_RECEIVE.png')
INVEST_SCROLL = Button(area=(1200, 153, 1203, 642), color=(148, 136, 148), button=(1200, 153, 1203, 642), file='./assets/cn/event_hospital/INVEST_SCROLL.png')
INVEST_SEARCH = Button(area=(261, 135, 1187, 636), color=(255, 255, 255), button=(261, 135, 1187, 636), file='./assets/cn/event_hospital/INVEST_SEARCH.png')
TAB_CHARACTER = Button(area=(263, 93, 409, 122), color=(185, 180, 191), button=(263, 93, 409, 122), file='./assets/cn/event_hospital/TAB_CHARACTER.png')
TAB_LOCATION = Button(area=(89, 93, 240, 121), color=(73, 108, 198), button=(89, 93, 240, 121), file='./assets/cn/event_hospital/TAB_LOCATION.png')
TEMPLATE_INVEST = Template(file={'cn': './assets/cn/event_hospital/TEMPLATE_INVEST.png', 'en': './assets/en/event_hospital/TEMPLATE_INVEST.png', 'jp': './assets/jp/event_hospital/TEMPLATE_INVEST.png', 'tw': './assets/tw/event_hospital/TEMPLATE_INVEST.png'})
TEMPLATE_INVEST2 = Template(file='./assets/cn/event_hospital/TEMPLATE_INVEST2.png')
TEMPLATE_REMAIN_CURRENT = Template(file={'cn': './assets/cn/event_hospital/TEMPLATE_REMAIN_CURRENT.png', 'en': './assets/en/event_hospital/TEMPLATE_REMAIN_CURRENT.png', 'jp': './assets/jp/event_hospital/TEMPLATE_REMAIN_CURRENT.png', 'tw': './assets/tw/event_hospital/TEMPLATE_REMAIN_CURRENT.png'})
TEMPLATE_REMAIN_TIMES = Template(file={'cn': './assets/cn/event_hospital/TEMPLATE_REMAIN_TIMES.png', 'en': './assets/en/event_hospital/TEMPLATE_REMAIN_TIMES.png', 'jp': './assets/jp/event_hospital/TEMPLATE_REMAIN_TIMES.png', 'tw': './assets/tw/event_hospital/TEMPLATE_REMAIN_TIMES.png'})
