from .classes import RogueResonance

# This file was auto-generated, do not modify it manually. To generate:
# ``` python -m dev_tools.keyword_extract ```

Path_Resonance_Preservation = RogueResonance(
    id=1,
    name='Path_Resonance_Preservation',
    cn='命途回响：「存护」',
    cht='命途迴響：「存護」',
    en='Path Resonance: Preservation',
    jp='運命の反響：「存護」',
    es='Resonancia de Vía: Conservación',
    path_id=1,
    rarity=3,
)
Resonance_Formation_Zero_Dimensional_Reinforcement = RogueResonance(
    id=2,
    name='Resonance_Formation_Zero_Dimensional_Reinforcement',
    cn='回响构音：零维强化',
    cht='迴響構音：零維強化',
    en='Resonance Formation: Zero-Dimensional Reinforcement',
    jp='反響構音：析出硬化',
    es='Formación de Resonancia: Potenciación de dimensión cero',
    path_id=1,
    rarity=3,
)
Resonance_Formation_Eutectic_Reaction = RogueResonance(
    id=3,
    name='Resonance_Formation_Eutectic_Reaction',
    cn='回响构音：共晶反应',
    cht='迴響構音：共晶反應',
    en='Resonance Formation: Eutectic Reaction',
    jp='反響構音：共晶反応',
    es='Formación de Resonancia: Reacción eutéctica',
    path_id=1,
    rarity=3,
)
Resonance_Formation_Isomorphous_Reaction = RogueResonance(
    id=4,
    name='Resonance_Formation_Isomorphous_Reaction',
    cn='回响构音：均晶转变',
    cht='迴響構音：均晶轉變',
    en='Resonance Formation: Isomorphous Reaction',
    jp='反響構音：全率固溶体',
    es='Formación de Resonancia: Reacción isomorfa',
    path_id=1,
    rarity=3,
)
Resonance_Interplay_Spiked_Armor = RogueResonance(
    id=5,
    name='Resonance_Interplay_Spiked_Armor',
    cn='回响交错：披锋效应',
    cht='迴響交錯：披鋒效應',
    en='Resonance Interplay: Spiked Armor',
    jp='反響交錯：トリミング加工',
    es='Interacción de Resonancia: Armadura de púas',
    path_id=1,
    rarity=3,
)
Resonance_Interplay_Cold_Snap = RogueResonance(
    id=6,
    name='Resonance_Interplay_Cold_Snap',
    cn='回响交错：冷脆现象',
    cht='迴響交錯：冷脆現象',
    en='Resonance Interplay: Cold Snap',
    jp='反響交錯：低温脆性',
    es='Interacción de Resonancia: Ola de frío',
    path_id=1,
    rarity=3,
)
Path_Resonance_Remembrance = RogueResonance(
    id=7,
    name='Path_Resonance_Remembrance',
    cn='命途回响：「记忆」',
    cht='命途迴響：「記憶」',
    en='Path Resonance: Remembrance',
    jp='運命の反響：「記憶」',
    es='Resonancia de Vía: Reminiscencia',
    path_id=2,
    rarity=3,
)
Resonance_Formation_Total_Recall = RogueResonance(
    id=8,
    name='Resonance_Formation_Total_Recall',
    cn='回响构音：全面回忆',
    cht='迴響構音：全面回憶',
    en='Resonance Formation: Total Recall',
    jp='反響構音：全面追憶',
    es='Formación de Resonancia: Desafío total',
    path_id=2,
    rarity=3,
)
Resonance_Formation_Rich_Experience = RogueResonance(
    id=9,
    name='Resonance_Formation_Rich_Experience',
    cn='回响构音：体验的富翁',
    cht='迴響構音：體驗的富翁',
    en='Resonance Formation: Rich Experience',
    jp='反響構音：体験の富豪',
    es='Formación de Resonancia: Experiencia acaudalada',
    path_id=2,
    rarity=3,
)
Resonance_Formation_First_Love_Once_More = RogueResonance(
    id=10,
    name='Resonance_Formation_First_Love_Once_More',
    cn='回响构音：第二次初恋',
    cht='迴響構音：第二次初戀',
    en='Resonance Formation: First Love Once More',
    jp='反響構音：二度目の初恋',
    es='Formación de Resonancia: Segundo amor',
    path_id=2,
    rarity=3,
)
Resonance_Interplay_Faces_Places = RogueResonance(
    id=11,
    name='Resonance_Interplay_Faces_Places',
    cn='回响交错：脸庞，村庄',
    cht='迴響交錯：臉龐，村莊',
    en='Resonance Interplay: Faces Places',
    jp='反響交錯：顔、村',
    es='Interacción de Resonancia: Lugares y rostros',
    path_id=2,
    rarity=3,
)
Resonance_Interplay_Landscape_in_the_Mist = RogueResonance(
    id=12,
    name='Resonance_Interplay_Landscape_in_the_Mist',
    cn='回响交错：雾中风景',
    cht='迴響交錯：霧中風景',
    en='Resonance Interplay: Landscape in the Mist',
    jp='反響交錯：霧の中の風景',
    es='Interacción de Resonancia: Paisaje en la niebla',
    path_id=2,
    rarity=3,
)
Path_Resonance_Nihility = RogueResonance(
    id=13,
    name='Path_Resonance_Nihility',
    cn='命途回响：「虚无」',
    cht='命途迴響：「虛無」',
    en='Path Resonance: Nihility',
    jp='運命の反響：「虚無」',
    es='Resonancia de Vía: Nihilidad',
    path_id=3,
    rarity=3,
)
Resonance_Formation_The_Doubtful_Fourfold_Root = RogueResonance(
    id=14,
    name='Resonance_Formation_The_Doubtful_Fourfold_Root',
    cn='回响构音：怀疑的四重根',
    cht='迴響構音：懷疑的四重根',
    en='Resonance Formation: The Doubtful Fourfold Root',
    jp='反響構音：疑いの四つの根',
    es='Formación de Resonancia: Raíz cuádruple dudosa',
    path_id=3,
    rarity=3,
)
Resonance_Formation_Suffering_and_Sunshine = RogueResonance(
    id=15,
    name='Resonance_Formation_Suffering_and_Sunshine',
    cn='回响构音：苦难与阳光',
    cht='迴響構音：苦難與陽光',
    en='Resonance Formation: Suffering and Sunshine',
    jp='反響構音：苦難と陽光',
    es='Formación de Resonancia: Sufrimiento y sol',
    path_id=3,
    rarity=3,
)
Resonance_Formation_Outsider = RogueResonance(
    id=16,
    name='Resonance_Formation_Outsider',
    cn='回响构音：局外人',
    cht='迴響構音：局外人',
    en='Resonance Formation: Outsider',
    jp='反響構音：異邦人',
    es='Formación de Resonancia: Ajeno',
    path_id=3,
    rarity=3,
)
Resonance_Interplay_Off_the_Beaten_Track = RogueResonance(
    id=17,
    name='Resonance_Interplay_Off_the_Beaten_Track',
    cn='回响交错：林中路',
    cht='迴響交錯：林中路',
    en='Resonance Interplay: Off the Beaten Track',
    jp='反響交錯：森の中の道',
    es='Interacción de Resonancia: Fuera de los caminos trillados',
    path_id=3,
    rarity=3,
)
Resonance_Interplay_White_Nights = RogueResonance(
    id=18,
    name='Resonance_Interplay_White_Nights',
    cn='回响交错：白夜',
    cht='迴響交錯：白夜',
    en='Resonance Interplay: White Nights',
    jp='反響交錯：白夜',
    es='Interacción de Resonancia: Noches blancas',
    path_id=3,
    rarity=3,
)
Path_Resonance_Abundance = RogueResonance(
    id=19,
    name='Path_Resonance_Abundance',
    cn='命途回响：「丰饶」',
    cht='命途迴響：「豐饒」',
    en='Path Resonance: Abundance',
    jp='運命の反響：「豊穣」',
    es='Resonancia de Vía: Abundancia',
    path_id=4,
    rarity=3,
)
Resonance_Formation_Terminal_Nirvana = RogueResonance(
    id=20,
    name='Resonance_Formation_Terminal_Nirvana',
    cn='回响构音：无余涅槃',
    cht='迴響構音：無餘涅槃',
    en='Resonance Formation: Terminal Nirvana',
    jp='反響構音：無余涅槃',
    es='Formación de Resonancia: Nirvana terminal',
    path_id=4,
    rarity=3,
)
Resonance_Formation_Anicca = RogueResonance(
    id=21,
    name='Resonance_Formation_Anicca',
    cn='回响构音：诸行无常',
    cht='迴響構音：諸行無常',
    en='Resonance Formation: Anicca',
    jp='反響構音：諸行無常',
    es='Formación de Resonancia: Anicca',
    path_id=4,
    rarity=3,
)
Resonance_Formation_Anatta = RogueResonance(
    id=22,
    name='Resonance_Formation_Anatta',
    cn='回响构音：诸法无我',
    cht='迴響構音：諸法無我',
    en='Resonance Formation: Anatta',
    jp='反響構音：諸法無我',
    es='Formación de Resonancia: Anatta',
    path_id=4,
    rarity=3,
)
Resonance_Interplay_First_Illuminate_the_Mountains = RogueResonance(
    id=23,
    name='Resonance_Interplay_First_Illuminate_the_Mountains',
    cn='回响交错：先照高山',
    cht='迴響交錯：先照高山',
    en='Resonance Interplay: First Illuminate the Mountains',
    jp='反響交錯：先に山を照らす',
    es='Interacción de Resonancia: Primero ilumina las montañas',
    path_id=4,
    rarity=3,
)
Resonance_Interplay_Nullifying_Ardor = RogueResonance(
    id=24,
    name='Resonance_Interplay_Nullifying_Ardor',
    cn='回响交错：旃檀薪尽',
    cht='迴響交錯：旃檀薪盡',
    en='Resonance Interplay: Nullifying Ardor',
    jp='反響交錯：センダンの薪尽きる',
    es='Interacción de Resonancia: Ardor anulador',
    path_id=4,
    rarity=3,
)
Path_Resonance_The_Hunt = RogueResonance(
    id=25,
    name='Path_Resonance_The_Hunt',
    cn='命途回响：「巡猎」',
    cht='命途迴響：「巡獵」',
    en='Path Resonance: The Hunt',
    jp='運命の反響：「巡狩」',
    es='Resonancia de Vía: Cacería',
    path_id=5,
    rarity=3,
)
Resonance_Formation_Star_Hunter = RogueResonance(
    id=26,
    name='Resonance_Formation_Star_Hunter',
    cn='回响构音：狩星巡日',
    cht='迴響構音：狩星巡日',
    en='Resonance Formation: Star Hunter',
    jp='反響構音：星を狩りて日を巡る',
    es='Formación de Resonancia: Caza de estrellas',
    path_id=5,
    rarity=3,
)
Resonance_Formation_Bow_and_Arrow = RogueResonance(
    id=27,
    name='Resonance_Formation_Bow_and_Arrow',
    cn='回响构音：柘弓危矢',
    cht='迴響構音：柘弓危矢',
    en='Resonance Formation: Bow and Arrow',
    jp='反響構音：柘弓に疾矢',
    es='Formación de Resonancia: Arco y flechas',
    path_id=5,
    rarity=3,
)
Resonance_Formation_Perfect_Aim = RogueResonance(
    id=28,
    name='Resonance_Formation_Perfect_Aim',
    cn='回响构音：射不主皮',
    cht='迴響構音：射不主皮',
    en='Resonance Formation: Perfect Aim',
    jp='反響構音：射は皮を主とせず',
    es='Formación de Resonancia: Diana perfecta',
    path_id=5,
    rarity=3,
)
Resonance_Interplay_Startling_Breeze = RogueResonance(
    id=29,
    name='Resonance_Interplay_Startling_Breeze',
    cn='回响交错：足逸惊飙',
    cht='迴響交錯：足逸驚飆',
    en='Resonance Interplay: Startling Breeze',
    jp='反響交錯：足元の突風',
    es='Interacción de Resonancia: Brisa sorprendente',
    path_id=5,
    rarity=3,
)
Resonance_Interplay_Shooting_Starfire = RogueResonance(
    id=30,
    name='Resonance_Interplay_Shooting_Starfire',
    cn='回响交错：火驰星流',
    cht='迴響交錯：火馳星流',
    en='Resonance Interplay: Shooting Starfire',
    jp='反響交錯：恒星ストリーム',
    es='Interacción de Resonancia: Fuego estelar',
    path_id=5,
    rarity=3,
)
Path_Resonance_Destruction = RogueResonance(
    id=31,
    name='Path_Resonance_Destruction',
    cn='命途回响：「毁灭」',
    cht='命途迴響：「毀滅」',
    en='Path Resonance: Destruction',
    jp='運命の反響：「壊滅」',
    es='Resonancia de Vía: Destrucción',
    path_id=6,
    rarity=3,
)
Resonance_Formation_Cataclysmic_Variable = RogueResonance(
    id=32,
    name='Resonance_Formation_Cataclysmic_Variable',
    cn='回响构音：激变变星',
    cht='迴響構音：激變變星',
    en='Resonance Formation: Cataclysmic Variable',
    jp='反響構音：激変星',
    es='Formación de Resonancia: Variable cataclísmica',
    path_id=6,
    rarity=3,
)
Resonance_Formation_Extreme_Helium_Flash = RogueResonance(
    id=33,
    name='Resonance_Formation_Extreme_Helium_Flash',
    cn='回响构音：极端氦闪',
    cht='迴響構音：極端氦閃',
    en='Resonance Formation: Extreme Helium Flash',
    jp='反響構音：ヘリウムフラッシュ',
    es='Formación de Resonancia: Fogonazo de helio',
    path_id=6,
    rarity=3,
)
Resonance_Formation_Event_Horizon = RogueResonance(
    id=34,
    name='Resonance_Formation_Event_Horizon',
    cn='回响构音：事件视界',
    cht='迴響構音：事件視界',
    en='Resonance Formation: Event Horizon',
    jp='反響構音：事象の地平線',
    es='Formación de Resonancia: Horizonte eventual',
    path_id=6,
    rarity=3,
)
Resonance_Interplay_Substellar_Belt = RogueResonance(
    id=35,
    name='Resonance_Interplay_Substellar_Belt',
    cn='回响交错：次行星带',
    cht='迴響交錯：次行星帶',
    en='Resonance Interplay: Substellar Belt',
    jp='反響交錯：準惑星帯',
    es='Interacción de Resonancia: Cinturón subestelar',
    path_id=6,
    rarity=3,
)
Resonance_Interplay_Zero_Age_Main_Sequence = RogueResonance(
    id=36,
    name='Resonance_Interplay_Zero_Age_Main_Sequence',
    cn='回响交错：零龄主序',
    cht='迴響交錯：零齡主序',
    en='Resonance Interplay: Zero Age Main Sequence',
    jp='反響交錯：零歳主系列',
    es='Interacción de Resonancia: Secuencia principal de la Era Cero',
    path_id=6,
    rarity=3,
)
Path_Resonance_Elation = RogueResonance(
    id=37,
    name='Path_Resonance_Elation',
    cn='命途回响：「欢愉」',
    cht='命途迴響：「歡愉」',
    en='Path Resonance: Elation',
    jp='運命の反響：「愉悦」',
    es='Resonancia de Vía: Exultación',
    path_id=7,
    rarity=3,
)
Resonance_Formation_Doomsday_Carnival = RogueResonance(
    id=38,
    name='Resonance_Formation_Doomsday_Carnival',
    cn='回响构音：末日狂欢',
    cht='迴響構音：末日狂歡',
    en='Resonance Formation: Doomsday Carnival',
    jp='反響構音：終末の狂宴',
    es='Formación de Resonancia: Fiesta del juicio final',
    path_id=7,
    rarity=3,
)
Resonance_Formation_Dance_of_Growth = RogueResonance(
    id=39,
    name='Resonance_Formation_Dance_of_Growth',
    cn='回响构音：树苗长高舞',
    cht='迴響構音：樹苗長高舞',
    en='Resonance Formation: Dance of Growth',
    jp='反響構音：苗木が育つ踊り',
    es='Formación de Resonancia; Danza de los brotes altos',
    path_id=7,
    rarity=3,
)
Resonance_Formation_Instant_Win = RogueResonance(
    id=40,
    name='Resonance_Formation_Instant_Win',
    cn='回响构音：开盖有奖',
    cht='迴響構音：開蓋有獎',
    en='Resonance Formation: Instant Win',
    jp='反響構音：もう1本',
    es='Formación de Resonancia: Abre y gana',
    path_id=7,
    rarity=3,
)
Resonance_Interplay_The_Taste_of_Anglerfish = RogueResonance(
    id=41,
    name='Resonance_Interplay_The_Taste_of_Anglerfish',
    cn='回响交错：安康鱼之味',
    cht='迴響交錯：鮟鱇魚之味',
    en='Resonance Interplay: The Taste of Anglerfish',
    jp='反響交錯：アンコウの味',
    es='Interacción de Resonancia: El sabor del rape',
    path_id=7,
    rarity=3,
)
Resonance_Interplay_Guinea_Pig_in_Ice_Coffin = RogueResonance(
    id=42,
    name='Resonance_Interplay_Guinea_Pig_in_Ice_Coffin',
    cn='回响交错：冰棺与豚鼠',
    cht='迴響交錯：冰棺與豚鼠',
    en='Resonance Interplay: Guinea Pig in Ice Coffin',
    jp='反響交錯：氷の棺とモルモット',
    es='Interacción de Resonancia: Cobayas en ataúdes de hielo',
    path_id=7,
    rarity=3,
)
Path_Resonance_Propagation = RogueResonance(
    id=43,
    name='Path_Resonance_Propagation',
    cn='命途回响：「繁育」',
    cht='命途迴響：「繁育」',
    en='Path Resonance: Propagation',
    jp='運命の反響：「繁殖」',
    es='Resonancia de Vía: Propagación',
    path_id=8,
    rarity=3,
)
Resonance_Formation_Proboscis = RogueResonance(
    id=44,
    name='Resonance_Formation_Proboscis',
    cn='回响构音：刺吸口器',
    cht='迴響構音：刺吸口器',
    en='Resonance Formation: Proboscis',
    jp='反響構音：吸収口器',
    es='Formación de Resonancia: Probóscide',
    path_id=8,
    rarity=3,
)
Resonance_Formation_Phenol_Compounds = RogueResonance(
    id=45,
    name='Resonance_Formation_Phenol_Compounds',
    cn='回响构音：酚类物质',
    cht='迴響構音：酚類物質',
    en='Resonance Formation: Phenol Compounds',
    jp='反響構音：フェノール類',
    es='Formación de Resonancia: Compuestos fenólicos',
    path_id=8,
    rarity=3,
)
Resonance_Formation_Crystal_Pincers = RogueResonance(
    id=46,
    name='Resonance_Formation_Crystal_Pincers',
    cn='回响构音：结晶螯刺',
    cht='迴響構音：結晶螯刺',
    en='Resonance Formation: Crystal Pincers',
    jp='反響構音：結晶毒針',
    es='Formación de Resonancia: Tenazas de cristal',
    path_id=8,
    rarity=3,
)
Resonance_Interplay_Superposition_Eye = RogueResonance(
    id=47,
    name='Resonance_Interplay_Superposition_Eye',
    cn='回响交错：重叠象眼',
    cht='迴響交錯：重疊象眼',
    en='Resonance Interplay: Superposition Eye',
    jp='反響交錯：重複像眼',
    es='Interacción de Resonancia: Ojo de superposición',
    path_id=8,
    rarity=3,
)
Resonance_Interplay_Adherent_Microbial_Mat = RogueResonance(
    id=48,
    name='Resonance_Interplay_Adherent_Microbial_Mat',
    cn='回响交错：附着菌毯',
    cht='迴響交錯：附著菌毯',
    en='Resonance Interplay: Adherent Microbial Mat',
    jp='反響交錯：菌膜付着',
    es='Interacción de Resonancia: Tapiz microbiano adherente',
    path_id=8,
    rarity=3,
)
