"""DeviceBase: the device contract used by the business layer (P2.4).

A structural Protocol describing the device surface that modules above
`module/device` rely on. `Device` structurally satisfies it; tests and
alternative backends can implement the same surface. Type checkers
(pyright) verify conformance at use sites.

Signatures are intentionally loose (`*args, **kwargs`): the protocol states
*which* capabilities exist, not their exact parameter lists — the concrete
backend owns the precise signatures (mixin layers differ per method).

Only the frequently used / stable surface is declared here (the 50 methods
touched by business code; the top ~25 cover >95% of call sites). Low-level
vendor specifics (u2, adb_shell, nemu_ipc, ...) intentionally stay on the
concrete classes — the protocol is the *business* contract, not the full
device capability list.
"""

from __future__ import annotations

import typing as t

import numpy as np

if t.TYPE_CHECKING:
    from module.config.config import AzurLaneConfig


class DeviceBase(t.Protocol):
    """Contract between the business layer and the device backend."""

    # --- config / state -------------------------------------------------
    config: AzurLaneConfig
    image: np.ndarray | None
    package: str
    hierarchy: t.Any  # lxml element tree root; set by AppControl

    # --- screenshots ----------------------------------------------------
    def screenshot(self, *args, **kwargs) -> np.ndarray: ...
    def has_cached_image(self, *args, **kwargs) -> bool: ...
    def screenshot_interval_set(self, *args, **kwargs) -> None: ...
    def save_screenshot(self, *args, **kwargs) -> None: ...

    # --- touch input ----------------------------------------------------
    def click(self, *args, **kwargs) -> None: ...
    def multi_click(self, *args, **kwargs) -> None: ...
    def long_click(self, *args, **kwargs) -> None: ...
    def drag(self, *args, **kwargs) -> None: ...
    def swipe(self, *args, **kwargs) -> None: ...
    def swipe_vector(self, *args, **kwargs) -> None: ...

    # --- time -----------------------------------------------------------
    def sleep(self, *args, **kwargs) -> None: ...

    # --- app control ----------------------------------------------------
    def app_start(self, *args, **kwargs) -> None: ...
    def app_stop(self, *args, **kwargs) -> None: ...
    def app_is_running(self, *args, **kwargs) -> bool: ...

    # --- click / stuck records ------------------------------------------
    def click_record_clear(self, *args, **kwargs) -> None: ...
    def click_record_add(self, *args, **kwargs) -> None: ...
    def click_record_remove(self, *args, **kwargs) -> None: ...
    def click_record_check(self, *args, **kwargs) -> bool: ...
    def stuck_record_clear(self, *args, **kwargs) -> None: ...
    def stuck_record_add(self, *args, **kwargs) -> None: ...
    def stuck_record_check(self, *args, **kwargs) -> bool: ...
    def disable_stuck_detection(self, *args, **kwargs) -> None: ...

    # --- misc -----------------------------------------------------------
    def get_orientation(self, *args, **kwargs) -> int: ...
    def dump_hierarchy(self, *args, **kwargs) -> t.Any: ...
    def release_during_wait(self, *args, **kwargs) -> None: ...
