from module.base.button import Button
from module.base.template import Template

# This file is generated by module.dev_tools.asset_extract.
# Don't modified it manually.

EQUIP_EDIT_ACTIVE = Button(area=(51, 608, 245, 668), color=(191, 159, 109), button=(51, 608, 245, 668), file='./assets/exercise/EQUIP_EDIT_ACTIVE.png')
EQUIP_EDIT_INACTIVE = Button(area=(51, 608, 246, 667), color=(89, 112, 158), button=(51, 608, 246, 667), file='./assets/exercise/EQUIP_EDIT_INACTIVE.png')
EQUIP_ENTER = Button(area=(351, 446, 361, 456), color=(252, 251, 252), button=(351, 446, 361, 456), file='./assets/exercise/EQUIP_ENTER.png')
EXERCISE_PREPARATION = Button(area=(543, 539, 741, 599), color=(235, 186, 114), button=(543, 539, 741, 599), file='./assets/exercise/EXERCISE_PREPARATION.png')
NEW_OPPONENT = Button(area=(1065, 340, 1204, 382), color=(129, 166, 220), button=(1065, 340, 1204, 382), file='./assets/exercise/NEW_OPPONENT.png')
OCR_EXERCISE_REMAIN = Button(area=(1148, 145, 1178, 160), color=(105, 148, 107), button=(1148, 145, 1178, 160), file='./assets/exercise/OCR_EXERCISE_REMAIN.png')
QUIT_CONFIRM = Button(area=(420, 490, 593, 548), color=(199, 122, 114), button=(420, 490, 593, 548), file='./assets/exercise/QUIT_CONFIRM.png')
QUIT_RECONFIRM = Button(area=(703, 492, 877, 550), color=(195, 111, 102), button=(703, 492, 877, 550), file='./assets/exercise/QUIT_RECONFIRM.png')
