from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

DATA_KEY_COLLECT = Button(
    area={
        "cn": (251, 38, 339, 73),
        "en": (256, 42, 337, 68),
        "jp": (254, 40, 340, 72),
        "tw": (251, 38, 339, 73),
    },
    color={
        "cn": (144, 116, 77),
        "en": (145, 109, 72),
        "jp": (144, 111, 69),
        "tw": (144, 116, 77),
    },
    button={
        "cn": (251, 38, 339, 73),
        "en": (256, 42, 337, 68),
        "jp": (254, 40, 340, 72),
        "tw": (251, 38, 339, 73),
    },
    file={
        "cn": "./assets/cn/data_key/DATA_KEY_COLLECT.png",
        "en": "./assets/en/data_key/DATA_KEY_COLLECT.png",
        "jp": "./assets/jp/data_key/DATA_KEY_COLLECT.png",
        "tw": "./assets/tw/data_key/DATA_KEY_COLLECT.png",
    },
)
DATA_KEY_COLLECTED = Button(
    area={
        "cn": (251, 38, 339, 73),
        "en": (255, 42, 338, 68),
        "jp": (254, 41, 340, 71),
        "tw": (251, 38, 339, 73),
    },
    color={
        "cn": (102, 103, 103),
        "en": (113, 113, 115),
        "jp": (102, 103, 103),
        "tw": (102, 103, 103),
    },
    button={
        "cn": (251, 38, 339, 73),
        "en": (255, 42, 338, 68),
        "jp": (254, 41, 340, 71),
        "tw": (251, 38, 339, 73),
    },
    file={
        "cn": "./assets/cn/data_key/DATA_KEY_COLLECTED.png",
        "en": "./assets/en/data_key/DATA_KEY_COLLECTED.png",
        "jp": "./assets/jp/data_key/DATA_KEY_COLLECTED.png",
        "tw": "./assets/tw/data_key/DATA_KEY_COLLECTED.png",
    },
)
OCR_DATA_KEY = Button(
    area={
        "cn": (132, 42, 233, 70),
        "en": (132, 42, 233, 70),
        "jp": (132, 42, 233, 70),
        "tw": (132, 42, 233, 70),
    },
    color={
        "cn": (74, 75, 86),
        "en": (74, 75, 86),
        "jp": (74, 75, 86),
        "tw": (74, 75, 86),
    },
    button={
        "cn": (132, 42, 233, 70),
        "en": (132, 42, 233, 70),
        "jp": (132, 42, 233, 70),
        "tw": (132, 42, 233, 70),
    },
    file={
        "cn": "./assets/cn/data_key/OCR_DATA_KEY.png",
        "en": "./assets/en/data_key/OCR_DATA_KEY.png",
        "jp": "./assets/jp/data_key/OCR_DATA_KEY.png",
        "tw": "./assets/tw/data_key/OCR_DATA_KEY.png",
    },
)
