from module.base.button import Button
from module.base.template import Template

# This file is generated by module.dev_tools.asset_extract.
# Don't modified it manually.

FLEET_1_BAR = Button(area=(1015, 244, 1186, 490), color=(171, 169, 170), button=(1015, 244, 1186, 490), file='./assets/map/FLEET_1_BAR.png')
FLEET_1_CHOOSE = Button(area=(1026, 166, 1089, 224), color=(209, 166, 106), button=(1026, 166, 1089, 224), file='./assets/map/FLEET_1_CHOOSE.png')
FLEET_1_CLEAR = Button(area=(1108, 166, 1172, 224), color=(154, 154, 156), button=(1108, 166, 1172, 224), file='./assets/map/FLEET_1_CLEAR.png')
FLEET_1_IN_USE = Button(area=(390, 158, 473, 241), color=(197, 171, 159), button=(390, 158, 473, 241), file='./assets/map/FLEET_1_IN_USE.png')
FLEET_2_BAR = Button(area=(1015, 377, 1186, 623), color=(180, 171, 155), button=(1015, 377, 1186, 623), file='./assets/map/FLEET_2_BAR.png')
FLEET_2_CHOOSE = Button(area=(1026, 299, 1089, 357), color=(208, 165, 105), button=(1026, 299, 1089, 357), file='./assets/map/FLEET_2_CHOOSE.png')
FLEET_2_CLEAR = Button(area=(1108, 299, 1172, 357), color=(153, 154, 156), button=(1108, 299, 1172, 357), file='./assets/map/FLEET_2_CLEAR.png')
FLEET_2_IN_USE = Button(area=(390, 291, 473, 374), color=(74, 66, 66), button=(390, 291, 473, 374), file='./assets/map/FLEET_2_IN_USE.png')
FLEET_PREPARATION = Button(area=(981, 575, 1180, 636), color=(235, 185, 114), button=(981, 575, 1180, 636), file='./assets/map/FLEET_PREPARATION.png')
FLEET_PREPARATION_HARD_1 = Button(area=(200, 260, 1004, 261), color=(247, 215, 0), button=(200, 260, 1004, 261), file='./assets/map/FLEET_PREPARATION_HARD_1.png')
FLEET_PREPARATION_HARD_2 = Button(area=(201, 393, 1001, 394), color=(255, 219, 0), button=(201, 393, 1001, 394), file='./assets/map/FLEET_PREPARATION_HARD_2.png')
MAP_CAT_ATTACK = Button(area=(1237, 103, 1252, 153), color=(43, 45, 52), button=(1148, 653, 1262, 705), file='./assets/map/MAP_CAT_ATTACK.png')
MAP_OFFENSIVE = Button(area=(1148, 653, 1262, 705), color=(234, 180, 108), button=(1148, 653, 1262, 705), file='./assets/map/MAP_OFFENSIVE.png')
MAP_PREPARATION = Button(area=(854, 488, 1052, 548), color=(236, 186, 115), button=(854, 488, 1052, 548), file='./assets/map/MAP_PREPARATION.png')
MAP_PREPARATION_CANCEL = Button(area=(234, 12, 278, 47), color=(45, 46, 69), button=(234, 12, 278, 47), file='./assets/map/MAP_PREPARATION_CANCEL.png')
SUBMARINE_BAR = Button(area=(1015, 525, 1186, 602), color=(193, 177, 144), button=(1015, 525, 1186, 602), file='./assets/map/SUBMARINE_BAR.png')
SUBMARINE_CHOOSE = Button(area=(1026, 447, 1090, 505), color=(208, 164, 103), button=(1026, 447, 1090, 505), file='./assets/map/SUBMARINE_CHOOSE.png')
SUBMARINE_CLEAR = Button(area=(1108, 447, 1172, 505), color=(152, 153, 154), button=(1108, 447, 1172, 505), file='./assets/map/SUBMARINE_CLEAR.png')
SUBMARINE_IN_USE = Button(area=(454, 439, 537, 521), color=(42, 54, 76), button=(454, 439, 537, 521), file='./assets/map/SUBMARINE_IN_USE.png')
SWITCH_OVER = Button(area=(947, 654, 1118, 706), color=(144, 158, 198), button=(947, 654, 1118, 706), file='./assets/map/SWITCH_OVER.png')
WITHDRAW = Button(area=(749, 654, 921, 707), color=(213, 124, 124), button=(749, 654, 921, 707), file='./assets/map/WITHDRAW.png')
