from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

BATTLE_PREPARATION = Button(area={'cn': (1031, 624, 1228, 682), 'en': (1031, 624, 1228, 682), 'jp': (1030, 623, 1229, 683), 'tw': (1031, 624, 1228, 682)}, color={'cn': (216, 159, 83), 'en': (216, 160, 91), 'jp': (214, 157, 83), 'tw': (216, 159, 83)}, button={'cn': (1031, 624, 1228, 682), 'en': (1031, 624, 1228, 682), 'jp': (1030, 623, 1229, 683), 'tw': (1031, 624, 1228, 682)}, file={'cn': './assets/cn/os_combat/BATTLE_PREPARATION.png', 'en': './assets/en/os_combat/BATTLE_PREPARATION.png', 'jp': './assets/jp/os_combat/BATTLE_PREPARATION.png', 'tw': './assets/tw/os_combat/BATTLE_PREPARATION.png'})
SIREN_PREPARATION = Button(area={'cn': (1043, 638, 1240, 698), 'en': (1043, 639, 1240, 698), 'jp': (1042, 638, 1241, 699), 'tw': (1047, 641, 1239, 698)}, color={'cn': (136, 94, 111), 'en': (131, 85, 102), 'jp': (136, 97, 113), 'tw': (138, 106, 121)}, button={'cn': (1043, 638, 1240, 698), 'en': (1043, 639, 1240, 698), 'jp': (1042, 638, 1241, 699), 'tw': (1047, 641, 1239, 698)}, file={'cn': './assets/cn/os_combat/SIREN_PREPARATION.png', 'en': './assets/en/os_combat/SIREN_PREPARATION.png', 'jp': './assets/jp/os_combat/SIREN_PREPARATION.png', 'tw': './assets/tw/os_combat/SIREN_PREPARATION.png'})
