from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools.button_extract.
# Don't modify it manually.

EFFICIENCY_SET_CHECK = Button(area={'cn': (906, 604, 922, 619), 'en': (906, 604, 922, 619), 'jp': (906, 604, 922, 619), 'tw': (906, 604, 922, 619)}, color={'cn': (29, 32, 29), 'en': (29, 32, 29), 'jp': (29, 32, 29), 'tw': (29, 32, 29)}, button={'cn': (906, 604, 922, 619), 'en': (906, 604, 922, 619), 'jp': (906, 604, 922, 619), 'tw': (906, 604, 922, 619)}, file={'cn': './assets/cn/efficiency/EFFICIENCY_SET_CHECK.png', 'en': './assets/cn/efficiency/EFFICIENCY_SET_CHECK.png', 'jp': './assets/cn/efficiency/EFFICIENCY_SET_CHECK.png', 'tw': './assets/cn/efficiency/EFFICIENCY_SET_CHECK.png'})
