dictionary_cn = {
    'major_comm': ['自主训练', '对抗演习', '科研任务', '工具整备', '战术课程', '货物运输'],
    'daily_resource': ['日常资源开发'],
    'daily_chip': ['高阶战术研发'],
    'extra_drill': ['航行训练', '防卫巡逻', '海域浮标检查作业'],
    'extra_part': ['委托'],
    'extra_cube': ['演习'],
    'extra_oil': ['油田'],
    'extra_book': ['商船护卫'],
    'urgent_drill': ['运输部队', '侦查部队', '主力部队', '精锐部队'],
    'urgent_part': ['维拉', '伊', '多伦瓦', '恐班纳', '马内', '萌'],
    'urgent_book': ['土豪尔', '姆波罗', '马拉基', '卡波罗', '玛丽', '特林'],
    'urgent_box': ['装备', '物资'],
    'urgent_cube': ['解救', '敌袭'],
    'urgent_gem': ['要员', '度假', '巡视'],
    'urgent_ship': ['观舰'],
}
# major_comm needs to be after extra_cube,
# because `Fleet Cargo Transport` is `extra_cube` and `Cargo Transport I` is major_comm
dictionary_en = {
    'daily_resource': ['AILY RESOURCE EXTRACTION'],
    'daily_chip': ['AKENING TACTICAL RESEARCH'],
    'extra_drill': ['SAILING', 'BUOY', 'FRONTIER', 'COASTAL', 'SALING'],
    'extra_part': ['VEIN', 'FOREST'],
    'extra_cube': ['FLEET ESCORT EXERCISE', 'FLEET EXERCISE', 'FLEET CARGO TRANSPORT', 'FLEET COMBAT EXERCISE'],
    'extra_oil': ['OIL'],
    'extra_book': ['MERCHANT ESCORT'],
    'urgent_drill': ['CARGO DEFENSE', 'DESTROY', 'COASTAL'],
    'urgent_part': ['LAVELLA', 'MAUI', 'RENDOVA', 'KONGBANNA', 'MANNE', 'ISLE'],
    'urgent_book': ['TYRANT', 'PORO', 'MAKIRA', 'KAPOLO', 'MARY', 'KOTLIN'],
    'urgent_box': ['GEAR', 'HANDOVER'],
    'urgent_cube': ['ENEMY ATTACK', 'MERCHANT RESCUE'],
    'urgent_gem': ['VIP', 'HOLIDAY ESCORT', 'PATROL ESCORT'],
    'urgent_ship': ['LAUNCH'],
    'major_comm': ['SELF TRAINING', 'DEFENSE EXERCISE', 'RESEARCH MISSION', 'TOOL PREP', 'TACTICAL CLASS',
                   'CARGO TRANSPORT'],
}
dictionary_jp = {
    'major_comm': ['初級自主訓練', '中級自主訓練', '上級自主訓練', '初級対抗演習', '中級対抗演習', '上級対抗演習',
                   '初級科学研究', '中級科学研究', '上級科学研究', '初級資材整理', '中級資材整理', '上級資材整理',
                   '初級戦術課程', '中級戦術課程', '上級戦術課程', '初級貨物輸送', '中級貨物輸送', '上級貨物輸送'],
    'daily_resource': ['日常資源開発'],
    'daily_chip': ['覚醒実証研究'],
    'extra_drill': ['短距離練習航海', '中距離練習航海', '外洋練習航海', '近海防衛巡回', '前線基地防衛巡回', '海域浮標保守作業'],
    'extra_part': ['初級木材輸送護衛', '中級木材輸送護衛', '上級木材輸送護衛', '初級鉄鋼輸送護衛', '中級鉄鋼輸送護衛',
                   '上級鉄鋼輸送護衛'],
    'extra_cube': ['船団護衛演習', '艦隊輸送演習', '艦隊実弾演習', '装備慣熟演習', '艦隊慣熟演習', '艦隊運動演習'],
    'extra_oil': ['小型油田開発', '中型油田開発', '大型油田開発'],
    'extra_book': ['小型船団護衛', '中型船団護衛', '大型船団護衛'],
    'urgent_drill': ['敵偵察部隊迎撃', '敵主力艦隊撃破', '敵精鋭部隊撃破', '輸送部隊護衛'],
    'urgent_part': ['近海掃海任務', '近海航行展示', '離島火力支援', '離島兵員輸送', '外敵生態調査', '兵站航路確保'],
    'urgent_book': ['離島物資輸送', '近海パトロール', '離島漸減支援', '外敵動静哨戒', '前線部隊支援', '外敵中枢偵察'],
    'urgent_box': ['装備輸送', '物資交換', '装備試験'],
    'urgent_cube': ['船団救出', '敵襲'],
    'urgent_gem': ['要人護衛', '休暇護衛'],
    'urgent_ship': ['小型観艦式', '連合艦隊観艦式', '多国連合観艦式'],
}
dictionary_tw = {
    'major_comm': ['自主訓練', '對抗演習', '科研任務', '工具整備', '戰術課程', '貨物運輸'],
    'daily_resource': ['日常資源開發'],
    'daily_chip': ['高階戰術研發'],
    'extra_drill': ['航行訓練', '防衛巡邏', '海域浮標檢查作業'],
    'extra_part': ['委託'],
    'extra_cube': ['演習'],
    'extra_oil': ['油田'],
    'extra_book': ['商船護衛'],
    'urgent_drill': ['運輸部隊', '偵查部隊', '主力部隊', '精銳部隊'],
    'urgent_part': ['維拉', '伊', '多倫瓦', '恐班納', '馬內', '萌'],
    'urgent_book': ['土豪爾', '姆波羅', '馬拉基', '卡波羅', '瑪麗', '特林'],
    'urgent_box': ['裝備', '物資'],
    'urgent_cube': ['解救', '敵襲'],
    'urgent_gem': ['要員', '度假', '巡視'],
    'urgent_ship': ['觀艦'],
}
