pip install --no-dependencies adbutils==0.11.0
pip install --no-dependencies aiofiles==0.7.0
pip install --no-dependencies anyio==1.3.1
pip install --no-dependencies apkutils2==1.0.0
pip install --no-dependencies asgiref==3.4.1
pip install --no-dependencies async-generator==1.10
pip install --no-dependencies atomicwrites==1.4.0
pip install --no-dependencies cached-property==1.5.2
pip install --no-dependencies certifi==2021.5.30
pip install --no-dependencies cffi==1.15.0
pip install --no-dependencies chardet==3.0.4
pip install --no-dependencies cigam==0.0.3
pip install --no-dependencies click==8.0.1
pip install --no-dependencies cnocr==1.2.2
pip install --no-dependencies colorama==0.4.4
pip install --no-dependencies commonmark==0.9.1
pip install --no-dependencies decorator==5.1.0
pip install --no-dependencies deprecated==1.2.13
pip install --no-dependencies deprecation==2.1.0
pip install --no-dependencies filelock==3.3.0
pip install --no-dependencies future==0.18.2
pip install --no-dependencies gevent==21.12.0
pip install --no-dependencies gluoncv==0.6.0
pip install --no-dependencies graphviz==0.8.4
pip install --no-dependencies greenlet==1.1.2
pip install --no-dependencies h11==0.12.0
pip install --no-dependencies httptools==0.4.0
pip install --no-dependencies idna==2.6
pip install --no-dependencies imageio==2.9.0
pip install --no-dependencies importlib-metadata==4.8.1
pip install --no-dependencies inflection==0.5.1
pip install --no-dependencies jellyfish==0.8.8
pip install --no-dependencies logzero==1.7.0
pip install --no-dependencies lz4==3.1.3
pip install --no-dependencies msgpack==1.0.3
pip install --no-dependencies mxnet==1.6.0
pip install --no-dependencies portalocker==2.3.2
pip install --no-dependencies prettytable==2.2.1
pip install --no-dependencies progress==1.6
pip install --no-dependencies py==1.10.0
pip install --no-dependencies pycparser==2.21
pip install --no-dependencies pyelftools==0.27
pip install --no-dependencies pygments==2.11.2
pip install --no-dependencies pypresence==4.2.1
pip install --no-dependencies python-dotenv==0.19.0
pip install --no-dependencies pywebio==1.5.2
pip install --no-dependencies pyyaml==5.4.1
pip install --no-dependencies requests==2.18.4
pip install --no-dependencies retry==0.9.2
pip install --no-dependencies retrying==1.3.3
pip install --no-dependencies rich==11.0.0
pip install --no-dependencies sniffio==1.2.0
pip install --no-dependencies starlette==0.14.2
pip install --no-dependencies tornado==6.1
pip install --no-dependencies tqdm==4.62.3
pip install --no-dependencies typing-extensions==3.10.0.2
pip install --no-dependencies ua-parser==0.10.0
pip install --no-dependencies uiautomator2==2.16.7
pip install --no-dependencies urllib3==1.22
pip install --no-dependencies user-agents==2.2.0
pip install --no-dependencies uvicorn[standard]==0.17.6
pip install --no-dependencies watchgod==0.7
pip install --no-dependencies wcwidth==0.2.5
pip install --no-dependencies websockets==10.0
pip install --no-dependencies whichcraft==0.6.1
pip install --no-dependencies wrapt==1.13.1
pip install --no-dependencies xmltodict==0.12.0
pip install --no-dependencies zerorpc==0.6.3
pip install --no-dependencies zipp==3.6.0
pip install --no-dependencies zope.event==4.5.0
pip install --no-dependencies zope.interface==5.4.0