from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

BATTLE_PASS_RED_DOT = Button(
    area={
        "cn": (623, 105, 629, 113),
        "en": (623, 105, 629, 113),
        "jp": (623, 105, 629, 113),
        "tw": (623, 105, 629, 113),
    },
    color={
        "cn": (202, 86, 66),
        "en": (202, 86, 66),
        "jp": (202, 86, 66),
        "tw": (202, 86, 66),
    },
    button={
        "cn": (623, 105, 629, 113),
        "en": (623, 105, 629, 113),
        "jp": (623, 105, 629, 113),
        "tw": (623, 105, 629, 113),
    },
    file={
        "cn": "./assets/cn/battle_pass/BATTLE_PASS_RED_DOT.png",
        "en": "./assets/en/battle_pass/BATTLE_PASS_RED_DOT.png",
        "jp": "./assets/jp/battle_pass/BATTLE_PASS_RED_DOT.png",
        "tw": "./assets/tw/battle_pass/BATTLE_PASS_RED_DOT.png",
    },
)
PURCHASE_POPUP = Button(
    area={
        "cn": (907, 204, 934, 229),
        "en": (907, 204, 934, 229),
        "jp": (907, 204, 934, 229),
        "tw": (907, 204, 934, 229),
    },
    color={
        "cn": (176, 130, 110),
        "en": (176, 130, 110),
        "jp": (176, 130, 110),
        "tw": (176, 130, 110),
    },
    button={
        "cn": (907, 204, 934, 229),
        "en": (907, 204, 934, 229),
        "jp": (907, 204, 934, 229),
        "tw": (907, 204, 934, 229),
    },
    file={
        "cn": "./assets/cn/battle_pass/PURCHASE_POPUP.png",
        "en": "./assets/en/battle_pass/PURCHASE_POPUP.png",
        "jp": "./assets/jp/battle_pass/PURCHASE_POPUP.png",
        "tw": "./assets/tw/battle_pass/PURCHASE_POPUP.png",
    },
)
REWARD_RECEIVE = Button(
    area={
        "cn": (1192, 520, 1255, 536),
        "en": (1192, 522, 1254, 534),
        "jp": (1186, 518, 1259, 536),
        "tw": (1192, 520, 1255, 536),
    },
    color={
        "cn": (191, 178, 163),
        "en": (195, 182, 168),
        "jp": (208, 197, 183),
        "tw": (191, 178, 163),
    },
    button={
        "cn": (1192, 520, 1255, 536),
        "en": (1192, 522, 1254, 534),
        "jp": (1186, 518, 1259, 536),
        "tw": (1192, 520, 1255, 536),
    },
    file={
        "cn": "./assets/cn/battle_pass/REWARD_RECEIVE.png",
        "en": "./assets/en/battle_pass/REWARD_RECEIVE.png",
        "jp": "./assets/jp/battle_pass/REWARD_RECEIVE.png",
        "tw": "./assets/cn/battle_pass/REWARD_RECEIVE.png",
    },
)
REWARD_RECEIVE_SP = Button(
    area={
        "cn": (1105, 579, 1184, 597),
        "en": (1090, 580, 1197, 596),
        "jp": (1091, 599, 1171, 618),
        "tw": (1105, 579, 1184, 597),
    },
    color={
        "cn": (178, 143, 126),
        "en": (168, 129, 111),
        "jp": (168, 127, 109),
        "tw": (178, 143, 126),
    },
    button={
        "cn": (1105, 579, 1184, 597),
        "en": (1090, 580, 1197, 596),
        "jp": (1091, 599, 1171, 618),
        "tw": (1105, 579, 1184, 597),
    },
    file={
        "cn": "./assets/cn/battle_pass/REWARD_RECEIVE_SP.png",
        "en": "./assets/en/battle_pass/REWARD_RECEIVE_SP.png",
        "jp": "./assets/jp/battle_pass/REWARD_RECEIVE_SP.png",
        "tw": "./assets/cn/battle_pass/REWARD_RECEIVE_SP.png",
    },
)
