from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

EQUIPMENT_OPEN = Button(
    area={
        "cn": (1195, 103, 1265, 134),
        "en": (1197, 107, 1262, 132),
        "jp": (1197, 106, 1265, 132),
        "tw": (1196, 114, 1263, 181),
    },
    color={
        "cn": (86, 141, 202),
        "en": (80, 140, 204),
        "jp": (82, 140, 203),
        "tw": (119, 161, 213),
    },
    button={
        "cn": (1195, 103, 1265, 134),
        "en": (1197, 107, 1262, 132),
        "jp": (1197, 106, 1265, 132),
        "tw": (1196, 114, 1263, 181),
    },
    file={
        "cn": "./assets/cn/equipment/EQUIPMENT_OPEN.png",
        "en": "./assets/en/equipment/EQUIPMENT_OPEN.png",
        "jp": "./assets/jp/equipment/EQUIPMENT_OPEN.png",
        "tw": "./assets/tw/equipment/EQUIPMENT_OPEN.png",
    },
)
EQUIPMENT_SCROLL_BOTTOM = Button(
    area={
        "cn": (1256, 575, 1264, 583),
        "en": (1256, 575, 1264, 583),
        "jp": (1256, 575, 1264, 583),
        "tw": (1256, 575, 1264, 583),
    },
    color={
        "cn": (244, 209, 66),
        "en": (244, 209, 66),
        "jp": (244, 209, 66),
        "tw": (244, 209, 66),
    },
    button={
        "cn": (1256, 575, 1264, 583),
        "en": (1256, 575, 1264, 583),
        "jp": (1256, 575, 1264, 583),
        "tw": (1256, 575, 1264, 583),
    },
    file={
        "cn": "./assets/cn/equipment/EQUIPMENT_SCROLL_BOTTOM.png",
        "en": "./assets/en/equipment/EQUIPMENT_SCROLL_BOTTOM.png",
        "jp": "./assets/jp/equipment/EQUIPMENT_SCROLL_BOTTOM.png",
        "tw": "./assets/tw/equipment/EQUIPMENT_SCROLL_BOTTOM.png",
    },
)
EQUIPPING_OFF = Button(
    area={
        "cn": (25, 565, 60, 589),
        "en": (30, 585, 59, 605),
        "jp": (25, 565, 60, 589),
        "tw": (25, 565, 60, 589),
    },
    color={
        "cn": (94, 101, 104),
        "en": (65, 70, 96),
        "jp": (94, 101, 104),
        "tw": (94, 101, 104),
    },
    button={
        "cn": (25, 565, 60, 589),
        "en": (30, 585, 59, 605),
        "jp": (25, 565, 60, 589),
        "tw": (25, 565, 60, 589),
    },
    file={
        "cn": "./assets/cn/equipment/EQUIPPING_OFF.png",
        "en": "./assets/en/equipment/EQUIPPING_OFF.png",
        "jp": "./assets/jp/equipment/EQUIPPING_OFF.png",
        "tw": "./assets/tw/equipment/EQUIPPING_OFF.png",
    },
)
EQUIPPING_ON = Button(
    area={
        "cn": (26, 485, 60, 510),
        "en": (32, 563, 54, 583),
        "jp": (26, 485, 60, 510),
        "tw": (26, 485, 60, 510),
    },
    color={
        "cn": (184, 191, 214),
        "en": (164, 173, 208),
        "jp": (184, 191, 214),
        "tw": (184, 191, 214),
    },
    button={
        "cn": (26, 486, 57, 584),
        "en": (7, 559, 78, 606),
        "jp": (26, 486, 57, 584),
        "tw": (26, 483, 61, 590),
    },
    file={
        "cn": "./assets/cn/equipment/EQUIPPING_ON.png",
        "en": "./assets/en/equipment/EQUIPPING_ON.png",
        "jp": "./assets/jp/equipment/EQUIPPING_ON.png",
        "tw": "./assets/tw/equipment/EQUIPPING_ON.png",
    },
)
EQUIP_1 = Button(
    area={
        "cn": (1218, 248, 1274, 302),
        "en": (1218, 285, 1273, 335),
        "jp": (1218, 247, 1276, 303),
        "tw": (1218, 249, 1274, 302),
    },
    color={
        "cn": (99, 143, 208),
        "en": (86, 139, 208),
        "jp": (97, 149, 217),
        "tw": (102, 152, 219),
    },
    button={
        "cn": (1218, 248, 1274, 302),
        "en": (1218, 285, 1273, 335),
        "jp": (1218, 247, 1276, 303),
        "tw": (1218, 249, 1274, 302),
    },
    file={
        "cn": "./assets/cn/equipment/EQUIP_1.png",
        "en": "./assets/en/equipment/EQUIP_1.png",
        "jp": "./assets/jp/equipment/EQUIP_1.png",
        "tw": "./assets/tw/equipment/EQUIP_1.png",
    },
)
EQUIP_2 = Button(
    area={
        "cn": (1218, 347, 1274, 403),
        "en": (1218, 374, 1273, 424),
        "jp": (1220, 350, 1273, 403),
        "tw": (1218, 349, 1274, 402),
    },
    color={
        "cn": (99, 142, 203),
        "en": (82, 132, 198),
        "jp": (98, 147, 214),
        "tw": (101, 150, 215),
    },
    button={
        "cn": (1218, 347, 1274, 403),
        "en": (1218, 374, 1273, 424),
        "jp": (1220, 350, 1273, 403),
        "tw": (1218, 349, 1274, 402),
    },
    file={
        "cn": "./assets/cn/equipment/EQUIP_2.png",
        "en": "./assets/en/equipment/EQUIP_2.png",
        "jp": "./assets/jp/equipment/EQUIP_2.png",
        "tw": "./assets/tw/equipment/EQUIP_2.png",
    },
)
EQUIP_3 = Button(
    area={
        "cn": (1218, 450, 1274, 504),
        "en": (1218, 464, 1273, 514),
        "jp": (1220, 450, 1275, 503),
        "tw": (1218, 450, 1274, 503),
    },
    color={
        "cn": (94, 138, 201),
        "en": (81, 130, 197),
        "jp": (94, 143, 210),
        "tw": (98, 145, 211),
    },
    button={
        "cn": (1218, 450, 1274, 504),
        "en": (1218, 464, 1273, 514),
        "jp": (1220, 450, 1275, 503),
        "tw": (1218, 450, 1274, 503),
    },
    file={
        "cn": "./assets/cn/equipment/EQUIP_3.png",
        "en": "./assets/en/equipment/EQUIP_3.png",
        "jp": "./assets/jp/equipment/EQUIP_3.png",
        "tw": "./assets/tw/equipment/EQUIP_3.png",
    },
)
EQUIP_CONFIRM = Button(
    area={
        "cn": (792, 623, 959, 677),
        "en": (795, 623, 960, 677),
        "jp": (792, 623, 960, 674),
        "tw": (792, 623, 960, 677),
    },
    color={
        "cn": (222, 154, 59),
        "en": (226, 160, 69),
        "jp": (222, 152, 55),
        "tw": (223, 153, 57),
    },
    button={
        "cn": (792, 623, 959, 677),
        "en": (795, 623, 960, 677),
        "jp": (792, 623, 960, 674),
        "tw": (792, 623, 960, 677),
    },
    file={
        "cn": "./assets/cn/equipment/EQUIP_CONFIRM.png",
        "en": "./assets/en/equipment/EQUIP_CONFIRM.png",
        "jp": "./assets/jp/equipment/EQUIP_CONFIRM.png",
        "tw": "./assets/tw/equipment/EQUIP_CONFIRM.png",
    },
)
EQUIP_OFF = Button(
    area={
        "cn": (933, 548, 1063, 593),
        "en": (921, 544, 1051, 588),
        "jp": (933, 549, 1064, 593),
        "tw": (936, 550, 1062, 592),
    },
    color={
        "cn": (107, 151, 216),
        "en": (97, 145, 203),
        "jp": (102, 148, 214),
        "tw": (107, 149, 213),
    },
    button={
        "cn": (933, 548, 1063, 593),
        "en": (921, 544, 1051, 588),
        "jp": (933, 549, 1064, 593),
        "tw": (936, 550, 1062, 592),
    },
    file={
        "cn": "./assets/cn/equipment/EQUIP_OFF.png",
        "en": "./assets/en/equipment/EQUIP_OFF.png",
        "jp": "./assets/jp/equipment/EQUIP_OFF.png",
        "tw": "./assets/tw/equipment/EQUIP_OFF.png",
    },
)
EQUIP_SAVE = Button(
    area={
        "cn": (355, 312, 452, 433),
        "en": (355, 312, 452, 433),
        "jp": (407, 312, 476, 404),
        "tw": (355, 312, 452, 433),
    },
    color={
        "cn": (170, 156, 122),
        "en": (170, 156, 122),
        "jp": (119, 94, 128),
        "tw": (170, 156, 122),
    },
    button={
        "cn": (355, 312, 452, 433),
        "en": (355, 312, 452, 433),
        "jp": (407, 312, 476, 404),
        "tw": (355, 312, 452, 433),
    },
    file={
        "cn": "./assets/cn/equipment/EQUIP_SAVE.png",
        "en": "./assets/en/equipment/EQUIP_SAVE.png",
        "jp": "./assets/jp/equipment/EQUIP_SAVE.png",
        "tw": "./assets/tw/equipment/EQUIP_SAVE.png",
    },
)
EQUIP_SCROLL = Button(
    area={
        "cn": (1254, 86, 1266, 588),
        "en": (1254, 86, 1266, 588),
        "jp": (1254, 86, 1266, 588),
        "tw": (1254, 86, 1266, 588),
    },
    color={
        "cn": (141, 130, 77),
        "en": (141, 130, 77),
        "jp": (141, 130, 77),
        "tw": (141, 130, 77),
    },
    button={
        "cn": (1254, 86, 1266, 588),
        "en": (1254, 86, 1266, 588),
        "jp": (1254, 86, 1266, 588),
        "tw": (1254, 86, 1266, 588),
    },
    file={
        "cn": "./assets/cn/equipment/EQUIP_SCROLL.png",
        "en": "./assets/en/equipment/EQUIP_SCROLL.png",
        "jp": "./assets/jp/equipment/EQUIP_SCROLL.png",
        "tw": "./assets/tw/equipment/EQUIP_SCROLL.png",
    },
)
EQUIP_TAKE_ON_0 = Button(
    area={
        "cn": (871, 151, 955, 244),
        "en": (871, 151, 955, 244),
        "jp": (871, 151, 955, 244),
        "tw": (871, 151, 955, 244),
    },
    color={
        "cn": (116, 113, 116),
        "en": (116, 113, 116),
        "jp": (116, 113, 116),
        "tw": (116, 113, 116),
    },
    button={
        "cn": (871, 151, 955, 244),
        "en": (871, 151, 955, 244),
        "jp": (871, 151, 955, 244),
        "tw": (871, 151, 955, 244),
    },
    file={
        "cn": "./assets/cn/equipment/EQUIP_TAKE_ON_0.png",
        "en": "./assets/en/equipment/EQUIP_TAKE_ON_0.png",
        "jp": "./assets/jp/equipment/EQUIP_TAKE_ON_0.png",
        "tw": "./assets/tw/equipment/EQUIP_TAKE_ON_0.png",
    },
)
EQUIP_TAKE_ON_1 = Button(
    area={
        "cn": (907, 338, 991, 431),
        "en": (907, 338, 991, 431),
        "jp": (907, 338, 991, 431),
        "tw": (907, 338, 991, 431),
    },
    color={
        "cn": (122, 122, 135),
        "en": (122, 122, 135),
        "jp": (122, 122, 135),
        "tw": (122, 122, 135),
    },
    button={
        "cn": (907, 338, 991, 431),
        "en": (907, 338, 991, 431),
        "jp": (907, 338, 991, 431),
        "tw": (907, 338, 991, 431),
    },
    file={
        "cn": "./assets/cn/equipment/EQUIP_TAKE_ON_1.png",
        "en": "./assets/en/equipment/EQUIP_TAKE_ON_1.png",
        "jp": "./assets/jp/equipment/EQUIP_TAKE_ON_1.png",
        "tw": "./assets/tw/equipment/EQUIP_TAKE_ON_1.png",
    },
)
EQUIP_TAKE_ON_2 = Button(
    area={
        "cn": (866, 511, 950, 604),
        "en": (866, 511, 950, 604),
        "jp": (866, 511, 950, 604),
        "tw": (866, 511, 950, 604),
    },
    color={
        "cn": (117, 118, 127),
        "en": (117, 118, 127),
        "jp": (117, 118, 127),
        "tw": (117, 118, 127),
    },
    button={
        "cn": (866, 511, 950, 604),
        "en": (866, 511, 950, 604),
        "jp": (866, 511, 950, 604),
        "tw": (866, 511, 950, 604),
    },
    file={
        "cn": "./assets/cn/equipment/EQUIP_TAKE_ON_2.png",
        "en": "./assets/en/equipment/EQUIP_TAKE_ON_2.png",
        "jp": "./assets/jp/equipment/EQUIP_TAKE_ON_2.png",
        "tw": "./assets/tw/equipment/EQUIP_TAKE_ON_2.png",
    },
)
EQUIP_TAKE_ON_3 = Button(
    area={
        "cn": (129, 252, 213, 345),
        "en": (129, 252, 213, 345),
        "jp": (129, 252, 213, 345),
        "tw": (129, 252, 213, 345),
    },
    color={
        "cn": (105, 108, 115),
        "en": (105, 108, 115),
        "jp": (105, 108, 115),
        "tw": (105, 108, 115),
    },
    button={
        "cn": (129, 252, 213, 345),
        "en": (129, 252, 213, 345),
        "jp": (129, 252, 213, 345),
        "tw": (129, 252, 213, 345),
    },
    file={
        "cn": "./assets/cn/equipment/EQUIP_TAKE_ON_3.png",
        "en": "./assets/en/equipment/EQUIP_TAKE_ON_3.png",
        "jp": "./assets/jp/equipment/EQUIP_TAKE_ON_3.png",
        "tw": "./assets/tw/equipment/EQUIP_TAKE_ON_3.png",
    },
)
EQUIP_TAKE_ON_4 = Button(
    area={
        "cn": (128, 432, 212, 525),
        "en": (128, 432, 212, 525),
        "jp": (128, 432, 212, 525),
        "tw": (128, 432, 212, 525),
    },
    color={
        "cn": (109, 111, 120),
        "en": (109, 111, 120),
        "jp": (109, 111, 120),
        "tw": (109, 111, 120),
    },
    button={
        "cn": (128, 432, 212, 525),
        "en": (128, 432, 212, 525),
        "jp": (128, 432, 212, 525),
        "tw": (128, 432, 212, 525),
    },
    file={
        "cn": "./assets/cn/equipment/EQUIP_TAKE_ON_4.png",
        "en": "./assets/en/equipment/EQUIP_TAKE_ON_4.png",
        "jp": "./assets/jp/equipment/EQUIP_TAKE_ON_4.png",
        "tw": "./assets/tw/equipment/EQUIP_TAKE_ON_4.png",
    },
)
FLEET_ENTER = Button(
    area={
        "cn": (502, 474, 517, 489),
        "en": (502, 474, 517, 489),
        "jp": (502, 474, 517, 489),
        "tw": (502, 474, 517, 489),
    },
    color={
        "cn": (58, 62, 77),
        "en": (58, 62, 77),
        "jp": (58, 62, 77),
        "tw": (58, 62, 77),
    },
    button={
        "cn": (502, 474, 517, 489),
        "en": (502, 474, 517, 489),
        "jp": (502, 474, 517, 489),
        "tw": (502, 474, 517, 489),
    },
    file={
        "cn": "./assets/cn/equipment/FLEET_ENTER.png",
        "en": "./assets/en/equipment/FLEET_ENTER.png",
        "jp": "./assets/jp/equipment/FLEET_ENTER.png",
        "tw": "./assets/tw/equipment/FLEET_ENTER.png",
    },
)
FLEET_ENTER_FLAGSHIP = Button(
    area={
        "cn": (577, 306, 604, 321),
        "en": (577, 306, 604, 321),
        "jp": (577, 306, 604, 321),
        "tw": (577, 306, 604, 321),
    },
    color={
        "cn": (95, 83, 74),
        "en": (95, 83, 74),
        "jp": (95, 83, 74),
        "tw": (95, 83, 74),
    },
    button={
        "cn": (577, 306, 604, 321),
        "en": (577, 306, 604, 321),
        "jp": (577, 306, 604, 321),
        "tw": (577, 306, 604, 321),
    },
    file={
        "cn": "./assets/cn/equipment/FLEET_ENTER_FLAGSHIP.png",
        "en": "./assets/en/equipment/FLEET_ENTER_FLAGSHIP.png",
        "jp": "./assets/jp/equipment/FLEET_ENTER_FLAGSHIP.png",
        "tw": "./assets/tw/equipment/FLEET_ENTER_FLAGSHIP.png",
    },
)
FLEET_NEXT = Button(
    area={
        "cn": (1234, 327, 1254, 356),
        "en": (1234, 327, 1254, 356),
        "jp": (1234, 327, 1254, 356),
        "tw": (1234, 327, 1254, 356),
    },
    color={
        "cn": (72, 93, 125),
        "en": (72, 93, 125),
        "jp": (72, 93, 125),
        "tw": (72, 93, 125),
    },
    button={
        "cn": (1234, 327, 1254, 356),
        "en": (1234, 327, 1254, 356),
        "jp": (1234, 327, 1254, 356),
        "tw": (1234, 327, 1254, 356),
    },
    file={
        "cn": "./assets/cn/equipment/FLEET_NEXT.png",
        "en": "./assets/en/equipment/FLEET_NEXT.png",
        "jp": "./assets/jp/equipment/FLEET_NEXT.png",
        "tw": "./assets/tw/equipment/FLEET_NEXT.png",
    },
)
FLEET_PREV = Button(
    area={
        "cn": (26, 327, 46, 356),
        "en": (26, 327, 46, 356),
        "jp": (26, 327, 46, 356),
        "tw": (26, 327, 46, 356),
    },
    color={
        "cn": (72, 93, 125),
        "en": (72, 93, 125),
        "jp": (72, 93, 125),
        "tw": (72, 93, 125),
    },
    button={
        "cn": (26, 327, 46, 356),
        "en": (26, 327, 46, 356),
        "jp": (26, 327, 46, 356),
        "tw": (26, 327, 46, 356),
    },
    file={
        "cn": "./assets/cn/equipment/FLEET_PREV.png",
        "en": "./assets/en/equipment/FLEET_PREV.png",
        "jp": "./assets/jp/equipment/FLEET_PREV.png",
        "tw": "./assets/tw/equipment/FLEET_PREV.png",
    },
)
OCR_FLEET_INDEX = Button(
    area={
        "cn": (957, 113, 987, 163),
        "en": (957, 113, 987, 163),
        "jp": (957, 113, 987, 163),
        "tw": (957, 113, 987, 163),
    },
    color={
        "cn": (36, 54, 86),
        "en": (36, 54, 86),
        "jp": (36, 54, 86),
        "tw": (36, 54, 86),
    },
    button={
        "cn": (957, 113, 987, 163),
        "en": (957, 113, 987, 163),
        "jp": (957, 113, 987, 163),
        "tw": (957, 113, 987, 163),
    },
    file={
        "cn": "./assets/cn/equipment/OCR_FLEET_INDEX.png",
        "en": "./assets/en/equipment/OCR_FLEET_INDEX.png",
        "jp": "./assets/jp/equipment/OCR_FLEET_INDEX.png",
        "tw": "./assets/tw/equipment/OCR_FLEET_INDEX.png",
    },
)
SHIP_INFO_EQUIPMENT_CHECK = Button(
    area={
        "cn": (1173, 654, 1216, 686),
        "en": (1173, 654, 1216, 686),
        "jp": (1173, 654, 1217, 687),
        "tw": (1173, 654, 1216, 686),
    },
    color={
        "cn": (216, 166, 94),
        "en": (216, 166, 94),
        "jp": (221, 167, 90),
        "tw": (216, 166, 94),
    },
    button={
        "cn": (1173, 654, 1216, 686),
        "en": (1173, 654, 1216, 686),
        "jp": (1173, 654, 1217, 687),
        "tw": (1173, 654, 1216, 686),
    },
    file={
        "cn": "./assets/cn/equipment/SHIP_INFO_EQUIPMENT_CHECK.png",
        "en": "./assets/en/equipment/SHIP_INFO_EQUIPMENT_CHECK.png",
        "jp": "./assets/jp/equipment/SHIP_INFO_EQUIPMENT_CHECK.png",
        "tw": "./assets/tw/equipment/SHIP_INFO_EQUIPMENT_CHECK.png",
    },
)
SWIPE_AREA = Button(
    area={
        "cn": (220, 167, 580, 527),
        "en": (220, 167, 580, 527),
        "jp": (220, 167, 580, 527),
        "tw": (220, 167, 580, 527),
    },
    color={
        "cn": (165, 172, 194),
        "en": (165, 172, 194),
        "jp": (165, 172, 194),
        "tw": (165, 172, 194),
    },
    button={
        "cn": (220, 167, 580, 527),
        "en": (220, 167, 580, 527),
        "jp": (220, 167, 580, 527),
        "tw": (220, 167, 580, 527),
    },
    file={
        "cn": "./assets/cn/equipment/SWIPE_AREA.png",
        "en": "./assets/en/equipment/SWIPE_AREA.png",
        "jp": "./assets/jp/equipment/SWIPE_AREA.png",
        "tw": "./assets/tw/equipment/SWIPE_AREA.png",
    },
)
SWIPE_CHECK = Button(
    area={
        "cn": (190, 353, 610, 455),
        "en": (190, 353, 610, 455),
        "jp": (190, 353, 610, 455),
        "tw": (190, 353, 610, 455),
    },
    color={
        "cn": (171, 180, 198),
        "en": (171, 180, 198),
        "jp": (171, 180, 198),
        "tw": (171, 180, 198),
    },
    button={
        "cn": (190, 353, 610, 455),
        "en": (190, 353, 610, 455),
        "jp": (190, 353, 610, 455),
        "tw": (190, 353, 610, 455),
    },
    file={
        "cn": "./assets/cn/equipment/SWIPE_CHECK.png",
        "en": "./assets/en/equipment/SWIPE_CHECK.png",
        "jp": "./assets/jp/equipment/SWIPE_CHECK.png",
        "tw": "./assets/tw/equipment/SWIPE_CHECK.png",
    },
)
UPGRADE_ENTER = Button(
    area={
        "cn": (759, 624, 919, 674),
        "en": (762, 623, 927, 677),
        "jp": (758, 622, 926, 672),
        "tw": (757, 624, 926, 674),
    },
    color={
        "cn": (228, 159, 66),
        "en": (228, 159, 69),
        "jp": (228, 156, 60),
        "tw": (229, 159, 64),
    },
    button={
        "cn": (759, 624, 919, 674),
        "en": (762, 623, 927, 677),
        "jp": (758, 622, 926, 672),
        "tw": (757, 624, 926, 674),
    },
    file={
        "cn": "./assets/cn/equipment/UPGRADE_ENTER.png",
        "en": "./assets/en/equipment/UPGRADE_ENTER.png",
        "jp": "./assets/jp/equipment/UPGRADE_ENTER.png",
        "tw": "./assets/tw/equipment/UPGRADE_ENTER.png",
    },
)
UPGRADE_ENTER_CHECK = Button(
    area={
        "cn": (825, 528, 859, 559),
        "en": (825, 528, 859, 559),
        "jp": (825, 528, 859, 559),
        "tw": (825, 528, 859, 559),
    },
    color={
        "cn": (163, 138, 71),
        "en": (163, 138, 71),
        "jp": (163, 138, 71),
        "tw": (163, 138, 71),
    },
    button={
        "cn": (825, 528, 859, 559),
        "en": (825, 528, 859, 559),
        "jp": (825, 528, 859, 559),
        "tw": (825, 528, 859, 559),
    },
    file={
        "cn": "./assets/cn/equipment/UPGRADE_ENTER_CHECK.png",
        "en": "./assets/en/equipment/UPGRADE_ENTER_CHECK.png",
        "jp": "./assets/jp/equipment/UPGRADE_ENTER_CHECK.png",
        "tw": "./assets/tw/equipment/UPGRADE_ENTER_CHECK.png",
    },
)
UPGRADE_QUIT = Button(
    area={
        "cn": (125, 81, 312, 639),
        "en": (125, 81, 312, 639),
        "jp": (125, 81, 312, 639),
        "tw": (125, 81, 312, 639),
    },
    color={
        "cn": (70, 72, 80),
        "en": (70, 72, 80),
        "jp": (70, 72, 80),
        "tw": (70, 72, 80),
    },
    button={
        "cn": (125, 81, 312, 639),
        "en": (125, 81, 312, 639),
        "jp": (125, 81, 312, 639),
        "tw": (125, 81, 312, 639),
    },
    file={
        "cn": "./assets/cn/equipment/UPGRADE_QUIT.png",
        "en": "./assets/en/equipment/UPGRADE_QUIT.png",
        "jp": "./assets/jp/equipment/UPGRADE_QUIT.png",
        "tw": "./assets/tw/equipment/UPGRADE_QUIT.png",
    },
)
