from module.base.button import Button
from module.base.template import Template

# This file is generated by module.dev_tools.asset_extract.
# Don't modified it manually.

EQUIPMENT_OPEN = Button(area=(1196, 114, 1263, 181), color=(119, 161, 213), button=(1196, 114, 1263, 181), file='./assets/equipment/EQUIPMENT_OPEN.png')
EQUIP_1 = Button(area=(1218, 249, 1274, 302), color=(102, 152, 219), button=(1218, 249, 1274, 302), file='./assets/equipment/EQUIP_1.png')
EQUIP_2 = Button(area=(1218, 349, 1274, 402), color=(101, 150, 215), button=(1218, 349, 1274, 402), file='./assets/equipment/EQUIP_2.png')
EQUIP_3 = Button(area=(1218, 450, 1274, 503), color=(98, 145, 211), button=(1218, 450, 1274, 503), file='./assets/equipment/EQUIP_3.png')
EQUIP_OFF = Button(area=(933, 548, 1063, 593), color=(107, 151, 216), button=(933, 548, 1063, 593), file='./assets/equipment/EQUIP_OFF.png')
FLEET_ENTER = Button(area=(502, 474, 517, 489), color=(58, 62, 77), button=(502, 474, 517, 489), file='./assets/equipment/FLEET_ENTER.png')
FLEET_NEXT = Button(area=(1234, 327, 1254, 356), color=(72, 93, 125), button=(1234, 327, 1254, 356), file='./assets/equipment/FLEET_NEXT.png')
FLEET_PREV = Button(area=(26, 327, 46, 356), color=(72, 93, 125), button=(26, 327, 46, 356), file='./assets/equipment/FLEET_PREV.png')
OCR_FLEET_INDEX = Button(area=(958, 124, 984, 155), color=(46, 72, 117), button=(958, 124, 984, 155), file='./assets/equipment/OCR_FLEET_INDEX.png')
SWIPE_AREA = Button(area=(220, 167, 580, 527), color=(165, 172, 194), button=(220, 167, 580, 527), file='./assets/equipment/SWIPE_AREA.png')
SWIPE_CHECK = Button(area=(190, 353, 610, 455), color=(171, 180, 198), button=(190, 353, 610, 455), file='./assets/equipment/SWIPE_CHECK.png')
