class Campaign(CampaignBase):
    def battle_0(self):
        if self.fleet_2_protect():
            return True
        if self.clear_siren():
            return True
        if self.clear_enemy(scale=(2,)):
            return True
        if self.clear_enemy(scale=(1,)):
            return True
        return self.battle_default()
    def battle_2(self):
        if self.clear_siren():
            return True
        if self.clear_enemy(scale=(2,)):
            return True
        if self.clear_enemy(scale=(1,)):
            return True
        return self.battle_default()
    def battle_5(self):
        if self.clear_enemy(scale=(1,)):
            return True
        if self.clear_enemy(scale=(2,)):
            return True
        return self.battle_default()
    def battle_6(self):
        return self.fleet_boss.clear_boss()
