import datetime

# This file was automatically generated by module/config/config_updater.py.
# Don't modify it manually.


class GeneratedConfig:
    """
    Auto generated configuration
    """

    # Group `Scheduler`
    Scheduler_Enable = False
    Scheduler_NextRun = datetime.datetime(2023, 1, 1, 5, 0)
    Scheduler_Command = 'Fpy'
    Scheduler_SuccessInterval = 60
    Scheduler_FailureInterval = 120
    Scheduler_ServerUpdate = '05:00'

    # Group `Emulator`
    Emulator_ServerName = 'disabled'

    # Group `Error`
    Error_SaveError = False
    Error_OnePushConfig = 'provider: null'

    # Group `Optimization`
    Optimization_WhenTaskQueueEmpty = 'stay_there'

    # Group `FpyEmulator`
    FpyEmulator_Serial = '127.0.0.1:5555'
    FpyEmulator_LaunchPath = '/absolute_path_to_FGO-py/deploy/AzurLaneAutoScript'

    # Group `FpyInterval`
    FpyInterval_Interval = '07:00'

    # Group `FpyTeam`
    FpyTeam_Index = 0

    # Group `FpyApple`
    FpyApple_AppleKind = 'gold'  # gold, silver, bronze, copper, quartz
    FpyApple_AppleCount = 0
    FpyApple_EatOnce = True
    FpyApple_AppleTotal = 999

    # Group `FpyLimit`
    FpyLimit_Defeated = True
    FpyLimit_KizunaReisou = True
    FpyLimit_SpecialDrop = 999

    # Group `FpyBenchmark`
    FpyBenchmark_BenchOption = 'all'  # touch, screen, all

    # Group `FpyCall`
    FpyCall_Function = 'lottery'  # fpSummon, lottery, mail, synthesis, summonHistory

    # Group `Storage`
    Storage_Storage = {}
