from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

BUY_CONFIRM = Button(
    area={
        "cn": (698, 579, 871, 636),
        "en": (710, 583, 860, 633),
        "jp": (697, 578, 872, 638),
        "tw": (699, 579, 869, 636),
    },
    color={
        "cn": (81, 129, 190),
        "en": (92, 142, 203),
        "jp": (80, 128, 189),
        "tw": (85, 132, 191),
    },
    button={
        "cn": (698, 579, 871, 636),
        "en": (710, 583, 860, 633),
        "jp": (697, 578, 872, 638),
        "tw": (699, 579, 869, 636),
    },
    file={
        "cn": "./assets/cn/supply_pack/BUY_CONFIRM.png",
        "en": "./assets/en/supply_pack/BUY_CONFIRM.png",
        "jp": "./assets/jp/supply_pack/BUY_CONFIRM.png",
        "tw": "./assets/tw/supply_pack/BUY_CONFIRM.png",
    },
)
FREE_SUPPLY_PACK = Button(
    area={
        "cn": (525, 533, 579, 560),
        "en": (523, 533, 582, 553),
        "jp": (523, 530, 583, 559),
        "tw": (524, 532, 582, 562),
    },
    color={
        "cn": (144, 154, 164),
        "en": (150, 160, 169),
        "jp": (123, 137, 148),
        "tw": (130, 143, 154),
    },
    button={
        "cn": (378, 155, 577, 352),
        "en": (426, 181, 557, 319),
        "jp": (373, 177, 583, 356),
        "tw": (388, 194, 554, 352),
    },
    file={
        "cn": "./assets/cn/supply_pack/FREE_SUPPLY_PACK.png",
        "en": "./assets/en/supply_pack/FREE_SUPPLY_PACK.png",
        "jp": "./assets/jp/supply_pack/FREE_SUPPLY_PACK.png",
        "tw": "./assets/tw/supply_pack/FREE_SUPPLY_PACK.png",
    },
)
