from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools.button_extract.
# Don't modify it manually.

BUY_CONFIRM = Button(area={'cn': (698, 579, 871, 636), 'en': (698, 579, 871, 636), 'jp': (698, 579, 871, 636), 'tw': (698, 579, 871, 636)}, color={'cn': (81, 129, 190), 'en': (81, 129, 190), 'jp': (81, 129, 190), 'tw': (81, 129, 190)}, button={'cn': (698, 579, 871, 636), 'en': (698, 579, 871, 636), 'jp': (698, 579, 871, 636), 'tw': (698, 579, 871, 636)}, file={'cn': './assets/cn/supply_pack/BUY_CONFIRM.png', 'en': './assets/cn/supply_pack/BUY_CONFIRM.png', 'jp': './assets/cn/supply_pack/BUY_CONFIRM.png', 'tw': './assets/cn/supply_pack/BUY_CONFIRM.png'})
FREE_SUPPLY_PACK = Button(area={'cn': (525, 533, 579, 560), 'en': (525, 533, 579, 560), 'jp': (525, 533, 579, 560), 'tw': (525, 533, 579, 560)}, color={'cn': (144, 154, 164), 'en': (144, 154, 164), 'jp': (144, 154, 164), 'tw': (144, 154, 164)}, button={'cn': (378, 155, 577, 352), 'en': (378, 155, 577, 352), 'jp': (378, 155, 577, 352), 'tw': (378, 155, 577, 352)}, file={'cn': './assets/cn/supply_pack/FREE_SUPPLY_PACK.png', 'en': './assets/cn/supply_pack/FREE_SUPPLY_PACK.png', 'jp': './assets/cn/supply_pack/FREE_SUPPLY_PACK.png', 'tw': './assets/cn/supply_pack/FREE_SUPPLY_PACK.png'})
