from module.base.button import Button
from module.base.template import Template

# This file is generated by module.dev_tools.asset_extract.
# Don't modified it manually.

OCR_ARCHIVES_REMAIN = Button(area={'cn': (158, 47, 183, 68), 'en': (158, 47, 183, 68)}, color={'cn': (158, 157, 164), 'en': (158, 157, 164)}, button={'cn': (158, 47, 183, 68), 'en': (158, 47, 183, 68)}, file={'cn': './assets/cn/war_archives/OCR_ARCHIVES_REMAIN.png', 'en': './assets/en/war_archives/OCR_ARCHIVES_REMAIN.png'})
