from module.base.button import Button
from module.base.template import Template

# This file is generated by module.dev_tools.asset_extract.
# Don't modified it manually.

DAILY_ACTIVE = Button(area=(611, 385, 711, 405), color=(5, 10, 7), button=(611, 385, 711, 405), file='./assets/daily/DAILY_ACTIVE.png')
DAILY_ENTER = Button(area=(534, 118, 744, 645), color=(136, 166, 185), button=(534, 118, 744, 645), file='./assets/daily/DAILY_ENTER.png')
DAILY_ENTER_CHECK = Button(area=(1222, 141, 1229, 150), color=(247, 209, 66), button=(1222, 141, 1229, 150), file='./assets/daily/DAILY_ENTER_CHECK.png')
DAILY_FLEET_NEXT = Button(area=(914, 325, 931, 354), color=(86, 115, 149), button=(914, 325, 931, 354), file='./assets/daily/DAILY_FLEET_NEXT.png')
DAILY_FLEET_PREV = Button(area=(36, 325, 53, 354), color=(103, 130, 163), button=(36, 325, 53, 354), file='./assets/daily/DAILY_FLEET_PREV.png')
DAILY_MISSION_1 = Button(area=(482, 140, 701, 255), color=(58, 80, 123), button=(482, 140, 701, 255), file='./assets/daily/DAILY_MISSION_1.png')
DAILY_MISSION_2 = Button(area=(482, 300, 701, 415), color=(61, 84, 128), button=(482, 300, 701, 415), file='./assets/daily/DAILY_MISSION_2.png')
DAILY_MISSION_3 = Button(area=(482, 460, 701, 575), color=(75, 106, 146), button=(482, 460, 701, 575), file='./assets/daily/DAILY_MISSION_3.png')
DAILY_NEXT = Button(area=(821, 161, 996, 604), color=(71, 48, 43), button=(821, 161, 996, 604), file='./assets/daily/DAILY_NEXT.png')
DAILY_PREV = Button(area=(282, 163, 456, 600), color=(60, 73, 71), button=(282, 163, 456, 600), file='./assets/daily/DAILY_PREV.png')
OCR_DAILY_FLEET_INDEX = Button(area=(524, 615, 562, 658), color=(66, 102, 158), button=(524, 615, 562, 658), file='./assets/daily/OCR_DAILY_FLEET_INDEX.png')
OCR_REMAIN = Button(area=(532, 119, 545, 141), color=(123, 151, 175), button=(532, 119, 545, 141), file='./assets/daily/OCR_REMAIN.png')
