from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ESCORT_CHECK = Button(
    area={
        "cn": (118, 15, 227, 40),
        "en": (128, 16, 346, 38),
        "jp": (117, 15, 227, 41),
        "tw": (118, 15, 227, 40),
    },
    color={
        "cn": (155, 171, 209),
        "en": (109, 126, 164),
        "jp": (150, 165, 200),
        "tw": (155, 171, 209),
    },
    button={
        "cn": (118, 15, 227, 40),
        "en": (128, 16, 346, 38),
        "jp": (117, 15, 227, 41),
        "tw": (118, 15, 227, 40),
    },
    file={
        "cn": "./assets/cn/event/ESCORT_CHECK.png",
        "en": "./assets/en/event/ESCORT_CHECK.png",
        "jp": "./assets/jp/event/ESCORT_CHECK.png",
        "tw": "./assets/tw/event/ESCORT_CHECK.png",
    },
)
ESCORT_HARD_ENTRANCE = Button(
    area={
        "cn": (118, 15, 227, 40),
        "en": (128, 16, 346, 38),
        "jp": (117, 15, 227, 41),
        "tw": (118, 15, 227, 40),
    },
    color={
        "cn": (155, 171, 209),
        "en": (109, 126, 164),
        "jp": (150, 165, 200),
        "tw": (155, 171, 209),
    },
    button={
        "cn": (745, 284, 886, 392),
        "en": (745, 284, 886, 392),
        "jp": (745, 284, 886, 392),
        "tw": (745, 284, 886, 392),
    },
    file={
        "cn": "./assets/cn/event/ESCORT_HARD_ENTRANCE.png",
        "en": "./assets/en/event/ESCORT_HARD_ENTRANCE.png",
        "jp": "./assets/jp/event/ESCORT_HARD_ENTRANCE.png",
        "tw": "./assets/tw/event/ESCORT_HARD_ENTRANCE.png",
    },
)
ESCORT_REMAIN = Button(
    area={
        "cn": (55, 673, 135, 694),
        "en": (41, 673, 113, 691),
        "jp": (29, 670, 125, 693),
        "tw": (55, 673, 135, 694),
    },
    color={
        "cn": (68, 96, 85),
        "en": (125, 142, 130),
        "jp": (125, 138, 134),
        "tw": (68, 96, 85),
    },
    button={
        "cn": (55, 673, 135, 694),
        "en": (41, 673, 113, 691),
        "jp": (29, 670, 125, 693),
        "tw": (55, 673, 135, 694),
    },
    file={
        "cn": "./assets/cn/event/ESCORT_REMAIN.png",
        "en": "./assets/en/event/ESCORT_REMAIN.png",
        "jp": "./assets/jp/event/ESCORT_REMAIN.png",
        "tw": "./assets/tw/event/ESCORT_REMAIN.png",
    },
)
MAIN_GOTO_ESCORT = Button(
    area={
        "cn": (609, 265, 654, 307),
        "en": (609, 265, 654, 307),
        "jp": (609, 265, 654, 307),
        "tw": (609, 265, 654, 307),
    },
    color={
        "cn": (216, 184, 171),
        "en": (216, 184, 171),
        "jp": (216, 184, 171),
        "tw": (216, 184, 171),
    },
    button={
        "cn": (609, 265, 654, 307),
        "en": (609, 265, 654, 307),
        "jp": (609, 265, 654, 307),
        "tw": (609, 265, 654, 307),
    },
    file={
        "cn": "./assets/cn/event/MAIN_GOTO_ESCORT.png",
        "en": "./assets/en/event/MAIN_GOTO_ESCORT.png",
        "jp": "./assets/jp/event/MAIN_GOTO_ESCORT.png",
        "tw": "./assets/tw/event/MAIN_GOTO_ESCORT.png",
    },
)
