from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

META_REWARD_NOTICE = Button(
    area={
        "cn": (1070, 508, 1075, 523),
        "en": (1070, 508, 1075, 523),
        "jp": (1070, 508, 1075, 523),
        "tw": (1070, 508, 1075, 523),
    },
    color={
        "cn": (249, 182, 57),
        "en": (249, 182, 57),
        "jp": (249, 182, 57),
        "tw": (249, 182, 57),
    },
    button={
        "cn": (1070, 508, 1075, 523),
        "en": (1070, 508, 1075, 523),
        "jp": (1070, 508, 1075, 523),
        "tw": (1070, 508, 1075, 523),
    },
    file={
        "cn": "./assets/cn/meta_reward/META_REWARD_NOTICE.png",
        "en": "./assets/en/meta_reward/META_REWARD_NOTICE.png",
        "jp": "./assets/jp/meta_reward/META_REWARD_NOTICE.png",
        "tw": "./assets/cn/meta_reward/META_REWARD_NOTICE.png",
    },
)
REWARD_CHECK = Button(
    area={
        "cn": (31, 486, 64, 543),
        "en": (35, 487, 62, 541),
        "jp": (31, 486, 64, 543),
        "tw": (31, 486, 64, 543),
    },
    color={
        "cn": (199, 164, 165),
        "en": (203, 169, 170),
        "jp": (206, 172, 174),
        "tw": (199, 164, 165),
    },
    button={
        "cn": (31, 486, 64, 543),
        "en": (35, 487, 62, 541),
        "jp": (31, 486, 64, 543),
        "tw": (31, 486, 64, 543),
    },
    file={
        "cn": "./assets/cn/meta_reward/REWARD_CHECK.png",
        "en": "./assets/en/meta_reward/REWARD_CHECK.png",
        "jp": "./assets/jp/meta_reward/REWARD_CHECK.png",
        "tw": "./assets/cn/meta_reward/REWARD_CHECK.png",
    },
)
REWARD_ENTER = Button(
    area={
        "cn": (1109, 535, 1187, 554),
        "en": (1106, 532, 1199, 544),
        "jp": (1108, 535, 1188, 554),
        "tw": (1109, 535, 1187, 554),
    },
    color={
        "cn": (199, 195, 201),
        "en": (213, 212, 217),
        "jp": (215, 207, 214),
        "tw": (199, 195, 201),
    },
    button={
        "cn": (1109, 535, 1187, 554),
        "en": (1106, 532, 1199, 544),
        "jp": (1108, 535, 1188, 554),
        "tw": (1109, 535, 1187, 554),
    },
    file={
        "cn": "./assets/cn/meta_reward/REWARD_ENTER.png",
        "en": "./assets/en/meta_reward/REWARD_ENTER.png",
        "jp": "./assets/jp/meta_reward/REWARD_ENTER.png",
        "tw": "./assets/cn/meta_reward/REWARD_ENTER.png",
    },
)
REWARD_RECEIVE = Button(
    area={
        "cn": (1031, 601, 1215, 638),
        "en": (1067, 608, 1182, 633),
        "jp": (1043, 604, 1203, 635),
        "tw": (1031, 601, 1215, 638),
    },
    color={
        "cn": (149, 62, 62),
        "en": (164, 92, 93),
        "jp": (150, 64, 64),
        "tw": (149, 62, 62),
    },
    button={
        "cn": (1031, 601, 1215, 638),
        "en": (1067, 608, 1182, 633),
        "jp": (1043, 604, 1203, 635),
        "tw": (1031, 601, 1215, 638),
    },
    file={
        "cn": "./assets/cn/meta_reward/REWARD_RECEIVE.png",
        "en": "./assets/en/meta_reward/REWARD_RECEIVE.png",
        "jp": "./assets/jp/meta_reward/REWARD_RECEIVE.png",
        "tw": "./assets/cn/meta_reward/REWARD_RECEIVE.png",
    },
)
