from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

CAMPAIGN_BONUS = Button(
    area={
        "cn": (404, 149, 439, 166),
        "en": (406, 150, 477, 162),
        "jp": (404, 150, 476, 167),
        "tw": (404, 149, 439, 166),
    },
    color={
        "cn": (188, 195, 207),
        "en": (199, 204, 212),
        "jp": (207, 211, 218),
        "tw": (188, 195, 207),
    },
    button={
        "cn": (404, 149, 439, 166),
        "en": (406, 150, 477, 162),
        "jp": (404, 150, 476, 167),
        "tw": (404, 149, 439, 166),
    },
    file={
        "cn": "./assets/cn/statistics/CAMPAIGN_BONUS.png",
        "en": "./assets/en/statistics/CAMPAIGN_BONUS.png",
        "jp": "./assets/jp/statistics/CAMPAIGN_BONUS.png",
        "tw": "./assets/cn/statistics/CAMPAIGN_BONUS.png",
    },
)
ENEMY_NAME = Button(
    area={
        "cn": (781, 283, 965, 322),
        "en": (781, 283, 965, 322),
        "jp": (781, 283, 965, 322),
        "tw": (781, 283, 965, 322),
    },
    color={
        "cn": (92, 102, 119),
        "en": (92, 102, 119),
        "jp": (92, 102, 119),
        "tw": (92, 102, 119),
    },
    button={
        "cn": (781, 283, 965, 322),
        "en": (781, 283, 965, 322),
        "jp": (781, 283, 965, 322),
        "tw": (781, 283, 965, 322),
    },
    file={
        "cn": "./assets/cn/statistics/ENEMY_NAME.png",
        "en": "./assets/en/statistics/ENEMY_NAME.png",
        "jp": "./assets/jp/statistics/ENEMY_NAME.png",
        "tw": "./assets/tw/statistics/ENEMY_NAME.png",
    },
)
GET_ITEMS_ODD = Button(
    area={
        "cn": (628, 294, 653, 397),
        "en": (628, 294, 653, 397),
        "jp": (628, 294, 653, 397),
        "tw": (628, 294, 653, 397),
    },
    color={
        "cn": (98, 103, 121),
        "en": (98, 103, 121),
        "jp": (98, 103, 121),
        "tw": (98, 103, 121),
    },
    button={
        "cn": (628, 294, 653, 397),
        "en": (628, 294, 653, 397),
        "jp": (628, 294, 653, 397),
        "tw": (628, 294, 653, 397),
    },
    file={
        "cn": "./assets/cn/statistics/GET_ITEMS_ODD.png",
        "en": "./assets/en/statistics/GET_ITEMS_ODD.png",
        "jp": "./assets/jp/statistics/GET_ITEMS_ODD.png",
        "tw": "./assets/tw/statistics/GET_ITEMS_ODD.png",
    },
)
